insert into districts (id, provinceId, vemisProvince, vemisId, vemisName, name, name2, displayOrder, keyword, name3, deletedAt)
values  (1, 58, '46', '481', 'Huyện A Lưới', 'Huyện A Lưới', 'A Lưới', null, '-481-Huyện A Lưới-A Lưới-', 'aluoi', null),
        (2, 34, '91', '908', 'Huyện An Biên', 'Huyện An Biên', 'An Biên', null, '-908-Huyện An Biên-An Biên-', 'anbien', null),
        (3, 28, '31', '309', 'Quận Dương Kinh', 'Quận Dương Kinh', 'Quận Dương Kinh', null, '-309-Quận Dương Kinh-An Dương-', 'quanduongkinh', null),
        (4, 21, '64', '623', 'Thị xã An Khê', 'Thị xã An Khê', 'An Khê', null, '-623-Thị xã An Khê-An Khê-', 'ankhe', null),
        (5, 28, '31', '313', 'Huyện An Lão', 'Huyện An Lão', 'An Lão', null, '-313-Huyện An Lão-An Lão-', 'anlao', null),
        (6, 11, '52', '542', 'Huyện An Lão', 'Huyện An Lão', 'An Lão', null, '-542-Huyện An Lão-An Lão-', 'anlao', null),
        (7, 34, '91', '909', 'Huyện An Minh', 'Huyện An Minh', 'An Minh', null, '-909-Huyện An Minh-An Minh-', 'anminh', null),
        (8, 11, '52', '549', 'Thị xã An Nhơn', 'Thị xã An Nhơn', 'An Nhơn', null, '-549-Thị xã An Nhơn-An Nhơn-', 'annhon', null),
        (9, 1, '89', '886', 'Huyện An Phú', 'Huyện An Phú', 'An Phú', null, '-886-Huyện An Phú-An Phú-', 'anphu', null),
        (10, 42, '40', '424', 'Huyện Anh Sơn', 'Huyện Anh Sơn', 'Anh Sơn', null, '-424-Huyện Anh Sơn-Anh Sơn-', 'anhson', null),
        (11, 21, '64', '624', 'Thị xã Ayun Pa', 'Thị xã Ayun Pa', 'Ayun Pa', null, '-624-Thị xã Ayun Pa-Ayun Pa-', 'ayunpa', null),
        (12, 32, '33', '329', 'Huyện Ân Thi', 'Huyện Ân Thi', 'Ân Thi', null, '-329-Huyện Ân Thi-Ân Thi-', 'anthi', null),
        (13, 4, '06', '061', 'Huyện Ba Bể', 'Huyện Ba Bể', 'Ba Bể', null, '-061-Huyện Ba Bể-Ba Bể-', 'babe', null),
        (14, 50, '22', '202', 'Huyện Ba Chẽ', 'Huyện Ba Chẽ', 'Ba Chẽ', null, '-202-Huyện Ba Chẽ-Ba Chẽ-', 'bache', null),
        (15, 24, '01', '001', 'Quận Ba Đình', 'Quận Ba Đình', 'Quận Ba Đình', null, '-001-Quận Ba Đình-Quận Ba Đình-', 'quanbadinh', null),
        (16, 49, '51', '535', 'Huyện Ba Tơ', 'Huyện Ba Tơ', 'Ba Tơ', null, '-535-Huyện Ba Tơ-Ba Tơ-', 'bato', null),
        (17, 7, '83', '836', 'Huyện Ba Tri', 'Huyện Ba Tri', 'Ba Tri', null, '-836-Huyện Ba Tri-Ba Tri-', 'batri', null),
        (18, 24, '01', '271', 'Huyện Ba Vì', 'Huyện Ba Vì', 'Ba Vì', null, '-271-Huyện Ba Vì-Ba Vì-', 'bavi', null),
        (19, 2, '77', '748', 'Thành phố Bà Rịa', 'Thành phố Bà Rịa', 'TP Bà Rịa', null, '-748-Thành phố Bà Rịa-', 'tpbaria', null),
        (20, 57, '38', '386', 'Huyện Bá Thước', 'Huyện Bá Thước', 'Bá Thước', null, '-386-Huyện Bá Thước-Bá Thước-', 'bathuoc', null),
        (21, 44, '58', '584', 'Huyện Bác Ái', 'Huyện Bác Ái', 'Bác Ái', null, '-584-Huyện Bác Ái-Bác Ái-', 'bacai', null),
        (22, 5, '95', '954', 'Thành phố Bạc Liêu', 'Thành phố Bạc Liêu', 'Bạc Liêu', null, '-954-Thành phố Bạc Liêu-Bạc Liêu-', 'baclieu', null),
        (23, 28, '31', '318', 'Huyện Bạch Long Vĩ', 'Huyện Bạch Long Vĩ', 'Bạch Long Vĩ', null, '-318-Huyện Bạch Long Vĩ-Bạch Long Vĩ-', 'bachlongvi', null),
        (24, 4, '06', '063', 'Huyện Bạch Thông', 'Huyện Bạch Thông', 'Bạch Thông', null, '-063-Huyện Bạch Thông-Bạch Thông-', 'bachthong', null),
        (25, 14, '04', '043', 'Huyện Bảo Lạc', 'Huyện Bảo Lạc', 'Bảo Lạc', null, '-043-Huyện Bảo Lạc-Bảo Lạc-', 'baolac', null),
        (26, 14, '04', '042', 'Huyện Bảo Lâm', 'Huyện Bảo Lâm', 'Bảo Lâm', null, '-042-Huyện Bảo Lâm-Bảo Lâm-', 'baolam', null),
        (27, 37, '68', '680', 'Huyện Bảo Lâm', 'Huyện Bảo Lâm', 'Bảo Lâm', null, '-680-Huyện Bảo Lâm-Bảo Lâm-', 'baolam', null),
        (28, 37, '68', '673', 'Thành phố Bảo Lộc', 'Thành phố Bảo Lộc', 'Bảo Lộc', null, '-673-Thành phố Bảo Lộc-Bảo Lộc-', 'baoloc', null),
        (29, 39, '10', '086', 'Huyện Bảo Thắng', 'Huyện Bảo Thắng', 'Bảo Thắng', null, '-086-Huyện Bảo Thắng-Bảo Thắng-', 'baothang', null),
        (30, 39, '10', '087', 'Huyện Bảo Yên', 'Huyện Bảo Yên', 'Bảo Yên', null, '-087-Huyện Bảo Yên-Bảo Yên-', 'baoyen', null),
        (31, 39, '10', '082', 'Huyện Bát Xát', 'Huyện Bát Xát', 'Bát Xát', null, '-082-Huyện Bát Xát-Bát Xát-', 'batxat', null),
        (32, 10, '60', '596', 'Huyện Bắc Bình', 'Huyện Bắc Bình', 'Bắc Bình', null, '-596-Huyện Bắc Bình-Bắc Bình-', 'bacbinh', null),
        (33, 3, '24', '213', 'Thành phố Bắc Giang', 'Thành phố Bắc Giang', 'Bắc Giang', null, '-213-Thành phố Bắc Giang-Bắc Giang-', 'bacgiang', null),
        (34, 39, '10', '085', 'Huyện Bắc Hà', 'Huyện Bắc Hà', 'Bắc Hà', null, '-085-Huyện Bắc Hà-Bắc Hà-', 'bacha', null),
        (35, 4, '06', '058', 'Thành phố Bắc Kạn', 'Thành phố Bắc Kạn', 'Bắc Kạn', null, '-058-Thành phố Bắc Kạn-Bắc Kạn-', 'backan', null),
        (36, 22, '02', '031', 'Huyện Bắc Mê', 'Huyện Bắc Mê', 'Bắc Mê', null, '-031-Huyện Bắc Mê-Bắc Mê-', 'bacme', null),
        (37, 6, '27', '256', 'Thành phố Bắc Ninh', 'Thành phố Bắc Ninh', 'Bắc Ninh', null, '-256-Thành phố Bắc Ninh-Bắc Ninh-', 'bacninh', null),
        (38, 22, '02', '034', 'Huyện Bắc Quang', 'Huyện Bắc Quang', 'Bắc Quang', null, '-034-Huyện Bắc Quang-Bắc Quang-', 'bacquang', null),
        (39, 38, '20', '185', 'Huyện Bắc Sơn', 'Huyện Bắc Sơn', 'Bắc Sơn', null, '-185-Huyện Bắc Sơn-Bắc Sơn-', 'bacson', null),
        (40, 48, '49', '515', 'Huyện Bắc Trà My', 'Huyện Bắc Trà My', 'Bắc Trà My', null, '-515-Huyện Bắc Trà My-Bắc Trà My-', 'bactramy', null),
        (41, 53, '14', '121', 'Huyện Bắc Yên', 'Huyện Bắc Yên', 'Bắc Yên', null, '-121-Huyện Bắc Yên-Bắc Yên-', 'bacyen', null),
        (42, 8, '74', '721', 'Thị xã Bến Cát', 'Thị xã Bến Cát', 'Bến Cát', null, '-721-Thị xã Bến Cát-Bến Cát-', 'bencat', null),
        (43, 54, '72', '711', 'Huyện Bến Cầu', 'Huyện Bến Cầu', 'Bến Cầu', null, '-711-Huyện Bến Cầu-Bến Cầu-', 'bencau', null),
        (44, 40, '80', '803', 'Huyện Bến Lức', 'Huyện Bến Lức', 'Bến Lức', null, '-803-Huyện Bến Lức-Bến Lức-', 'benluc', null),
        (45, 7, '83', '829', 'Thành phố Bến Tre', 'Thành phố Bến Tre', 'TP Bến Tre', null, '-829-Thành phố Bến Tre-Bến Tre-', 'tpbentre', null),
        (46, 19, '75', '731', 'Thành phố Biên Hòa', 'Thành phố Biên Hòa', 'Biên Hòa', null, '-731-Thành phố Biên Hòa-Biên Hòa-', 'bienhoa', null),
        (47, 57, '38', '381', 'Thị xã Bỉm Sơn', 'Thị xã Bỉm Sơn', 'Bỉm Sơn', null, '-381-Thị xã Bỉm Sơn-Bỉm Sơn-', 'bimson', null),
        (48, 30, '79', '785', 'Huyện Bình Chánh', 'Huyện Bình Chánh', 'Bình Chánh', null, '-785-Huyện Bình Chánh-Bình Chánh-', 'binhchanh', null),
        (49, 7, '83', '835', 'Huyện Bình Đại', 'Huyện Bình Đại', 'Bình Đại', null, '-835-Huyện Bình Đại-Bình Đại-', 'binhdai', null),
        (50, 38, '20', '181', 'Huyện Bình Gia', 'Huyện Bình Gia', 'Bình Gia', null, '-181-Huyện Bình Gia-Bình Gia-', 'binhgia', null),
        (51, 27, '30', '296', 'Huyện Bình Giang', 'Huyện Bình Giang', 'Bình Giang', null, '-296-Huyện Bình Giang-Bình Giang-', 'binhgiang', null),
        (52, 50, '22', '198', 'Huyện Bình Liêu', 'Huyện Bình Liêu', 'Bình Liêu', null, '-198-Huyện Bình Liêu-Bình Liêu-', 'binhlieu', null),
        (53, 9, '70', '690', 'Thị xã Bình Long', 'Thị xã Bình Long', 'Bình Long', null, '-690-Thị xã Bình Long-Bình Long-', 'binhlong', null),
        (54, 23, '35', '352', 'Huyện Bình Lục', 'Huyện Bình Lục', 'Bình Lục', null, '-352-Huyện Bình Lục-Bình Lục-', 'binhluc', null),
        (55, 62, '86', '861', 'Thị xã Bình Minh', 'Thị xã Bình Minh', 'Bình Minh', null, '-861-Huyện Bình Minh-Bình Minh-Thị xã Bình Minh-', 'binhminh', null),
        (56, 49, '51', '524', 'Huyện Bình Sơn', 'Huyện Bình Sơn', 'Bình Sơn', null, '-524-Huyện Bình Sơn-Bình Sơn-', 'binhson', null),
        (57, 30, '79', '777', 'Quận Bình Tân', 'Quận Bình Tân', 'Quận Bình Tân', null, '-777-Quận Bình Tân-Quận Bình Tân-', 'quanbinhtan', null),
        (58, 62, '86', '863', 'Huyện Bình Tân', 'Huyện Bình Tân', 'Bình Tân', null, '-863-Huyện Bình Tân-Bình Tân-', 'binhtan', null),
        (59, 30, '79', '765', 'Quận Bình Thạnh', 'Quận Bình Thạnh', 'Quận Bình Thạnh', null, '-765-Quận Bình Thạnh-Quận Bình Thạnh-', 'quanbinhthanh', null),
        (60, 13, '92', '918', 'Quận Bình Thủy', 'Quận Bình Thủy', 'Quận Bình Thủy', null, '-918-Quận Bình Thuỷ-Quận Bình Thủy-', 'quanbinhthuy', null),
        (61, 63, '26', '249', 'Huyện Bình Xuyên', 'Huyện Bình Xuyên', 'Bình Xuyên', null, '-249-Huyện Bình Xuyên-Bình Xuyên-', 'binhxuyen', null),
        (62, 47, '44', '455', 'Huyện Bố Trạch', 'Huyện Bố Trạch', 'Bố Trạch', null, '-455-Huyện Bố Trạch-Bố Trạch-', 'botrach', null),
        (63, 9, '70', '696', 'Huyện Bù Đăng', 'Huyện Bù Đăng', 'Bù Đăng', null, '-696-Huyện Bù Đăng-Bù Đăng-', 'budang', null),
        (64, 9, '70', '693', 'Huyện Bù Đốp', 'Huyện Bù Đốp', 'Bù Đốp', null, '-693-Huyện Bù Đốp-Bù Đốp-', 'budop', null),
        (65, 9, '70', '691', 'Huyện Bù Gia Mập', 'Huyện Bù Gia Mập', 'Bù Gia Mập', null, '-691-Huyện Bù Gia Mập-Bù Gia Mập-', 'bugiamap', null),
        (66, 16, '66', '647', 'Huyện Buôn Đôn', 'Huyện Buôn Đôn', 'Buôn Đôn', null, '-647-Huyện Buôn Đôn-Buôn Đôn-', 'buondon', null),
        (67, 16, '66', '644', 'Thị Xã Buôn Hồ', 'Thị Xã Buôn Hồ', 'TX Buôn Hồ', null, '-644-Thị Xã Buôn Hồ-Buôn Hồ-', 'txbuonho', null),
        (68, 16, '66', '643', 'Thành phố Buôn Ma Thuột', 'Thành phố Buôn Ma Thuột', 'Buôn Ma Thuột', null, '-643-Thành phố Buôn Ma Thuột-Buôn Ma Thuột-', 'buonmathuot', null),
        (69, 12, '96', '964', 'Thành phố Cà Mau', 'Thành phố Cà Mau', 'Cà Mau', null, '-964-Thành phố Cà Mau-Cà Mau-', 'camau', null),
        (70, 59, '82', '820', 'Huyện Cai Lậy', 'Huyện Cai Lậy', 'Cai Lậy', null, '-820-Huyện Cai Lậy-Cai Lậy-', 'cailay', null),
        (71, 59, '82', '819', 'Huyện Cái Bè', 'Huyện Cái Bè', 'Cái Bè', null, '-819-Huyện Cái Bè-Cái Bè-', 'caibe', null),
        (72, 12, '96', '969', 'Huyện Cái Nước', 'Huyện Cái Nước', 'Cái Nước', null, '-969-Huyện Cái Nước-Cái Nước-', 'cainuoc', null),
        (73, 13, '92', '919', 'Quận Cái Răng', 'Quận Cái Răng', 'Quận Cái Răng', null, '-919-Quận Cái Răng-Quận Cái Răng-', 'quancairang', null),
        (74, 33, '56', '570', 'Huyện Cam Lâm', 'Huyện Cam Lâm', 'Cam Lâm', null, '-570-Huyện Cam Lâm-Cam Lâm-', 'camlam', null),
        (75, 51, '45', '468', 'Huyện Cam Lộ', 'Huyện Cam Lộ', 'Cam Lộ', null, '-468-Huyện Cam Lộ-Cam Lộ-', 'camlo', null),
        (76, 33, '56', '569', 'Thành phố Cam Ranh', 'Thành phố Cam Ranh', 'Cam Ranh', null, '-569-Thành phố Cam Ranh-Cam Ranh-', 'camranh', null),
        (77, 26, '42', '443', 'Huyện Can Lộc', 'Huyện Can Lộc', 'Can Lộc', null, '-443-Huyện Can Lộc-Can Lộc-', 'canloc', null),
        (78, 60, '84', '844', 'Huyện Càng Long', 'Huyện Càng Long', 'Càng Long', null, '-844-Huyện Càng Long-Càng Long-', 'canglong', null),
        (79, 14, '04', '040', 'Tp. Cao Bằng', 'Tp. Cao Bằng', 'Cao Bằng', null, '-040-Thị xã Cao Bằng-Cao Bằng-', 'caobang', null),
        (80, 20, '87', '866', 'Thành phố Cao Lãnh', 'Thành phố Cao Lãnh', 'TP Cao Lãnh', null, '-866-Thành phố Cao Lãnh-Cao Lãnh-', 'tpcaolanh', null),
        (82, 38, '20', '183', 'Huyện Cao Lộc', 'Huyện Cao Lộc', 'Cao Lộc', null, '-183-Huyện Cao Lộc-Cao Lộc-', 'caoloc', null),
        (83, 31, '17', '154', 'Huyện Cao Phong', 'Huyện Cao Phong', 'Cao Phong', null, '-154-Huyện Cao Phong-Cao Phong-', 'caophong', null),
        (84, 28, '31', '317', 'Huyện Cát Hải', 'Huyện Cát Hải', 'Cát Hải', null, '-317-Huyện Cát Hải-Cát Hải-', 'cathai', null),
        (85, 37, '68', '683', 'Huyện Cát Tiên', 'Huyện Cát Tiên', 'Cát Tiên', null, '-683-Huyện Cát Tiên-Cát Tiên-', 'cattien', null),
        (86, 27, '30', '295', 'Huyện Cẩm Giàng', 'Huyện Cẩm Giàng', 'Cẩm Giàng', null, '-295-Huyện Cẩm Giàng-Cẩm Giàng-', 'camgiang', null),
        (87, 45, '25', '235', 'Huyện Cẩm Khê', 'Huyện Cẩm Khê', 'Cẩm Khê', null, '-235-Huyện Cẩm Khê-Cẩm Khê-', 'camkhe', null),
        (88, 15, '48', '495', 'Quận Cẩm Lệ', 'Quận Cẩm Lệ', 'Cẩm Lệ', null, '-495-Quận Cẩm Lệ-Quận Cẩm Lệ-', 'camle', null),
        (89, 19, '75', '739', 'Huyện Cẩm Mỹ', 'Huyện Cẩm Mỹ', 'Cẩm Mỹ', null, '-739-Huyện Cẩm Mỹ-Cẩm Mỹ-', 'cammy', null),
        (90, 50, '22', '195', 'Thị xã Cẩm Phả', 'Thị xã Cẩm Phả', 'Cẩm Phả', null, '-195-Thị xã Cẩm Phả-Cẩm Phả-', 'campha', null),
        (91, 57, '38', '390', 'Huyện Cẩm Thủy', 'Huyện Cẩm Thủy', 'Cẩm Thủy', null, '-390-Huyện Cẩm Thủy-Cẩm Thủy-', 'camthuy', null),
        (92, 26, '42', '446', 'Huyện Cẩm Xuyên', 'Huyện Cẩm Xuyên', 'Cẩm Xuyên', null, '-446-Huyện Cẩm Xuyên-Cẩm Xuyên-', 'camxuyen', null),
        (93, 40, '80', '806', 'Huyện Cần Đước', 'Huyện Cần Đước', 'Cần Đước', null, '-806-Huyện Cần Đước-Cần Đước-', 'canduoc', null),
        (94, 30, '79', '787', 'Huyện Cần Giờ', 'Huyện Cần Giờ', 'Cần Giờ', null, '-787-Huyện Cần Giờ-Cần Giờ-', 'cangio', null),
        (95, 40, '80', '807', 'Huyện Cần Giuộc', 'Huyện Cần Giuộc', 'Cần Giuộc', null, '-807-Huyện Cần Giuộc-Cần Giuộc-', 'cangiuoc', null),
        (96, 24, '01', '005', 'Quận Cầu Giấy', 'Quận Cầu Giấy', 'Quận Cầu Giấy', null, '-005-Quận Cầu Giấy-Quận Cầu Giấy-', 'quancaugiay', null),
        (97, 60, '84', '845', 'Huyện Cầu Kè', 'Huyện Cầu Kè', 'Cầu Kè', null, '-845-Huyện Cầu Kè-Cầu Kè-', 'cauke', null),
        (98, 60, '84', '848', 'Huyện Cầu Ngang', 'Huyện Cầu Ngang', 'Cầu Ngang', null, '-848-Huyện Cầu Ngang-Cầu Ngang-', 'caungang', null),
        (99, 1, '89', '884', 'Tp. Châu Đốc', 'Tp. Châu Đốc', 'TP Châu Đốc', null, '-884-Tp. Châu Đốc-Châu Đốc-', 'tpchaudoc', null),
        (100, 2, '77', '750', 'Huyện Châu Đức', 'Huyện Châu Đức', 'Châu Đức', null, '-750-Huyện Châu Đức-Châu Đức-', 'chauduc', null),
        (101, 1, '89', '889', 'Huyện Châu Phú', 'Huyện Châu Phú', 'Châu Phú', null, '-889-Huyện Châu Phú-Châu Phú-', 'chauphu', null),
        (102, 1, '89', '892', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-892-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (103, 7, '83', '831', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-831-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (104, 20, '87', '877', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-877-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (105, 29, '93', '933', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-932-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (106, 34, '91', '905', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-905-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (107, 40, '80', '808', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-808-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (108, 52, '94', '942', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-942-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (109, 54, '72', '708', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-708-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (110, 59, '82', '821', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-821-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (111, 60, '84', '847', 'Huyện Châu Thành', 'Huyện Châu Thành', 'Châu Thành', null, '-847-Huyện Châu Thành-Châu Thành-', 'chauthanh', null),
        (112, 29, '93', '932', 'Huyện Châu Thành A', 'Huyện Châu Thành A', 'Châu Thành A', null, '-932-Huyện Châu Thành A-Châu Thành A-', 'chauthanha', null),
        (113, 38, '20', '187', 'Huyện Chi Lăng', 'Huyện Chi Lăng', 'Chi Lăng', null, '-187-Huyện Chi Lăng-Chi Lăng-', 'chilang', null),
        (114, 27, '30', '290', 'Thị xã Chí Linh', 'Thị xã Chí Linh', 'Chí Linh', null, '-290-Thị xã Chí Linh-Chí Linh-', 'chilinh', null),
        (115, 61, '08', '073', 'Huyện Chiêm Hóa', 'Huyện Chiêm Hóa', 'Chiêm Hóa', null, '-073-Huyện Chiêm Hóa-Chiêm Hóa-', 'chiemhoa', null),
        (116, 4, '06', '064', 'Huyện Chợ Đồn', 'Huyện Chợ Đồn', 'Chợ Đồn', null, '-064-Huyện Chợ Đồn-Chợ Đồn-', 'chodon', null),
        (117, 59, '82', '822', 'Huyện Chợ Gạo', 'Huyện Chợ Gạo', 'Chợ Gạo', null, '-822-Huyện Chợ Gạo-Chợ Gạo-', 'chogao', null),
        (118, 7, '83', '832', 'Huyện Chợ Lách', 'Huyện Chợ Lách', 'Chợ Lách', null, '-832-Huyện Chợ Lách-Chợ Lách-', 'cholach', null),
        (119, 4, '06', '065', 'Huyện Chợ Mới', 'Huyện Chợ Mới', 'Chợ Mới', null, '-065-Huyện Chợ Mới-Chợ Mới-', 'chomoi', null),
        (120, 1, '89', '893', 'Huyện Chợ Mới', 'Huyện Chợ Mới', 'Chợ Mới', null, '-893-Huyện Chợ Mới-Chợ Mới-', 'chomoi', null),
        (121, 9, '70', '697', 'Huyện Chơn Thành', 'Huyện Chơn Thành', 'Chơn Thành', null, '-697-Huyện Chơn Thành-Chơn Thành-', 'chonthanh', null),
        (122, 21, '64', '627', 'Huyện Chư Păh', 'Huyện Chư Păh', 'Chư Păh', null, '-627-Huyện Chư Păh-Chư Păh-', 'chupah', null),
        (123, 21, '64', '632', 'Huyện Chư Prông', 'Huyện Chư Prông', 'Chư Prông', null, '-632-Huyện Chư Prông-Chư Prông-', 'chuprong', null),
        (124, 21, '64', '639', 'Huyện Chư Pưh', 'Huyện Chư Pưh', 'Chư Pưh', null, '-639-Huyện Chư Pưh-Chư Pưh-', 'chupuh', null),
        (125, 21, '64', '633', 'Huyện Chư Sê', 'Huyện Chư Sê', 'Chư Sê', null, '-633-Huyện Chư Sê-Chư Sê-', 'chuse', null),
        (126, 24, '01', '277', 'Huyện Chương Mỹ', 'Huyện Chương Mỹ', 'Chương Mỹ', null, '-277-Huyện Chương Mỹ-Chương Mỹ-', 'chuongmy', null),
        (127, 42, '40', '422', 'Huyện Con Cuông', 'Huyện Con Cuông', 'Con Cuông', null, '-422-Huyện Con Cuông-Con Cuông-', 'concuong', null),
        (128, 50, '22', '207', 'Huyện Cô Tô', 'Huyện Cô Tô', 'Cô Tô', null, '-207-Huyện Cô Tô-Cô Tô-', 'coto', null),
        (129, 2, '77', '755', 'Huyện Côn Đảo', 'Huyện Côn Đảo', 'Côn Đảo', null, '-755-Huyện Côn Đảo-Côn Đảo-', 'condao', null),
        (130, 51, '45', '471', 'Huyện Cồn Cỏ', 'Huyện Cồn Cỏ', 'Cồn Cỏ', null, '-471-Huyện Cồn Cỏ-Cồn Cỏ-', 'conco', null),
        (131, 13, '92', '925', 'Huyện Cờ Đỏ', 'Huyện Cờ Đỏ', 'Cờ Đỏ', null, '-925-Huyện Cờ Đỏ-Cờ Đỏ-', 'codo', null),
        (132, 52, '94', '945', 'Huyện Cù Lao Dung', 'Huyện Cù Lao Dung', 'Cù Lao Dung', null, '-945-Huyện Cù Lao Dung-Cù Lao Dung-', 'culaodung', null),
        (133, 30, '79', '783', 'Huyện Củ Chi', 'Huyện Củ Chi', 'Củ Chi', null, '-783-Huyện Củ Chi-Củ Chi-', 'cuchi', null),
        (134, 16, '66', '657', 'Huyện Cư Kuin', 'Huyện Cư Kuin', 'Cư Kuin', null, '-657-Huyện Cư Kuin-Cư Kuin-', 'cukuin', null),
        (135, 17, '67', '662', 'Huyện Cư Jút', 'Huyện Cư Jút', 'Cư Jút', null, '-662-Huyện Cư Jút-Cư Jút-', 'cujut', null),
        (136, 16, '66', '648', 'Huyện Cư M''gar', 'Huyện Cư M''gar', 'Cư M''gar', null, '-648-Huyện Cư M''gar-Cư M''gar-', 'cumgar', null),
        (137, 42, '40', '413', 'Thị xã Cửa Lò', 'Thị xã Cửa Lò', 'Cửa Lò', null, '-413-Thị xã Cửa Lò-Cửa Lò-', 'cualo', null),
        (138, 8, '74', '720', 'Huyện Dầu Tiếng', 'Huyện Dầu Tiếng', 'Dầu Tiếng', null, '-720-Huyện Dầu Tiếng-Dầu Tiếng-', 'dautieng', null),
        (139, 37, '68', '679', 'Huyện Di Linh', 'Huyện Di Linh', 'Di Linh', null, '-679-Huyện Di Linh-Di Linh-', 'dilinh', null),
        (140, 8, '74', '724', 'Thị xã Dĩ An', 'Thị xã Dĩ An', 'Dĩ An', null, '-724-Thị xã Dĩ An-Dĩ An-', 'dian', null),
        (141, 33, '56', '574', 'Huyện Diên Khánh', 'Huyện Diên Khánh', 'Diên Khánh', null, '-574-Huyện Diên Khánh-Diên Khánh-', 'dienkhanh', null),
        (142, 42, '40', '425', 'Huyện Diễn Châu', 'Huyện Diễn Châu', 'Diễn Châu', null, '-425-Huyện Diễn Châu-Diễn Châu-', 'dienchau', null),
        (143, 23, '35', '349', 'Huyện Duy Tiên', 'Huyện Duy Tiên', 'Duy Tiên', null, '-349-Huyện Duy Tiên-Duy Tiên-', 'duytien', null),
        (144, 48, '49', '508', 'Huyện Duy Xuyên', 'Huyện Duy Xuyên', 'Duy Xuyên', null, '-508-Huyện Duy Xuyên-Duy Xuyên-', 'duyxuyen', null),
        (146, 28, '31', '312', 'Huyện An Dương', 'Huyện An Dương', 'An Dương', null, '-309-Huyện An Dương-Huyện An Dương-', 'anduong', null),
        (147, 54, '72', '707', 'Huyện Dương Minh Châu', 'Huyện Dương Minh Châu', 'Dương Minh Châu', null, '-707-Huyện Dương Minh Châu-Dương Minh Châu-', 'duongminhchau', null),
        (148, 51, '45', '467', 'Huyện Đa Krông', 'Huyện Đa Krông', 'Đa Krông', null, '-467-Huyện Đa Krông-Đa Krông-', 'dakrong', null),
        (149, 31, '17', '150', 'Huyện Đà Bắc', 'Huyện Đà Bắc', 'Đà Bắc', null, '-150-Huyện Đà Bắc-Đà Bắc-', 'dabac', null),
        (150, 37, '68', '672', 'Thành phố Đà Lạt', 'Thành phố Đà Lạt', 'Đà Lạt', null, '-672-Thành phố Đà Lạt-Đà Lạt-', 'dalat', null),
        (151, 37, '68', '681', 'Huyện Đạ Huoai', 'Huyện Đạ Huoai', 'Đạ Huoai', null, '-681-Huyện Đạ Huoai-Đạ Huoai-', 'dahuoai', null),
        (152, 37, '68', '682', 'Huyện Đạ Tẻh', 'Huyện Đạ Tẻh', 'Đạ Tẻh', null, '-682-Huyện Đạ Tẻh-Đạ Tẻh-', 'dateh', null),
        (153, 48, '49', '506', 'Huyện Đại Lộc', 'Huyện Đại Lộc', 'Đại Lộc', null, '-506-Huyện Đại Lộc-Đại Lộc-', 'dailoc', null),
        (154, 56, '19', '171', 'Huyện Đại Từ', 'Huyện Đại Từ', 'Đại Từ', null, '-171-Huyện Đại Từ-Đại Từ-', 'daitu', null),
        (155, 21, '64', '626', 'Huyện Đăk Đoa', 'Huyện Đăk Đoa', 'Đăk Đoa', null, '-626-Huyện Đăk Đoa-Đăk Đoa-', 'dakdoa', null),
        (156, 21, '64', '634', 'Huyện Đăk Pơ', 'Huyện Đăk Pơ', 'Đăk Pơ', null, '-634-Huyện Đăk Pơ-Đắk Pơ-', 'dakpo', null),
        (157, 24, '01', '273', 'Huyện Đan Phượng', 'Huyện Đan Phượng', 'Đan Phượng', null, '-273-Huyện Đan Phượng-Đan Phượng-', 'danphuong', null),
        (158, 35, '62', '610', 'Huyện Đắk Glei', 'Huyện Đắk Glei', 'Đắk Glei', null, '-610-Huyện Đắk Glei-Đắk Glei-', 'dakglei', null),
        (159, 17, '67', '661', 'Huyện Đăk Glong', 'Huyện Đăk Glong', 'Đăk Glong', null, '-661-Huyện Đăk Glong-Đăk Glong-', 'dakglong', null),
        (160, 35, '62', '615', 'Huyện Đắk Hà', 'Huyện Đắk Hà', 'Đắk Hà', null, '-615-Huyện Đắk Hà-Đắk Hà-', 'dakha', null),
        (161, 17, '67', '663', 'Huyện Đắk Mil', 'Huyện Đắk Mil', 'Đắk Mil', null, '-663-Huyện Đắk Mil-Đăk Mil-', 'dakmil', null),
        (162, 17, '67', '666', 'Huyện Đắk R''Lấp', 'Huyện Đắk R''Lấp', 'Đắk R''Lấp', null, '-666-Huyện Đắk R''Lấp-Đăk R''Lấp-', 'dakrlap', null),
        (163, 17, '67', '665', 'Huyện Đắk Song', 'Huyện Đắk Song', 'Đắk Song', null, '-665-Huyện Đắk Song-Đăk Song-', 'daksong', null),
        (164, 35, '62', '612', 'Huyện Đắk Tô', 'Huyện Đắk Tô', 'Đắk Tô', null, '-612-Huyện Đắk Tô-Đăk Tô-', 'dakto', null),
        (165, 12, '96', '970', 'Huyện Đầm Dơi', 'Huyện Đầm Dơi', 'Đầm Dơi', null, '-970-Huyện Đầm Dơi-Đầm Dơi-', 'damdoi', null),
        (166, 50, '22', '200', 'Huyện Đầm Hà', 'Huyện Đầm Hà', 'Đầm Hà', null, '-200-Huyện Đầm Hà-Đầm Hà-', 'damha', null),
        (167, 37, '68', '674', 'Huyện Đam Rông', 'Huyện Đam Rông', 'Đam Rông', null, '-674-Huyện Đam Rông-Đam Rông-', 'damrong', null),
        (168, 2, '77', '753', 'Huyện Đất Đỏ', 'Huyện Đất Đỏ', 'Đất Đỏ', null, '-753-Huyện Đất Đỏ-Đất Đỏ-', 'datdo', null),
        (169, 48, '49', '507', 'Thị xã Điện Bàn', 'Thị Xã Điện Bàn', 'Điện Bàn', null, '-507-Huyện Điện Bàn-Điện Bàn-', 'dienban', null),
        (170, 18, '11', '094', 'Thành phố Điện Biên Phủ', 'Thành phố Điện Biên Phủ', 'Điện Biên Phủ', null, '-094-Thành phố Điện Biên Phủ-Điện Biên-', 'dienbienphu', null),
        (171, 18, '11', '101', 'Huyện Điện Biên Đông', 'Huyện Điện Biên Đông', 'Điện Biên Đông', null, '-101-Huyện Điện Biên Đông-Điện Biên Đông-', 'dienbiendong', null),
        (172, 18, '11', '100', 'Huyện Điện Biên', 'Huyện Điện Biên', 'Điện Biên Phủ', null, '-100-Huyện Điện Biên-Điện Biên Phủ-', 'dienbienphu', null),
        (173, 38, '20', '189', 'Huyện Đình Lập', 'Huyện Đình Lập', 'Đình Lập', null, '-189-Huyện Đình Lập-Đình Lập-', 'dinhlap', null),
        (174, 56, '19', '167', 'Huyện Định Hóa', 'Huyện Định Hóa', 'Định Hóa', null, '-167-Huyện Định Hóa-Định Hóa-', 'dinhhoa', null),
        (175, 19, '75', '736', 'Huyện Định Quán', 'Huyện Định Quán', 'Định Quán', null, '-736-Huyện Định Quán-Định Quán-', 'dinhquan', null),
        (176, 45, '25', '230', 'Huyện Đoan Hùng', 'Huyện Đoan Hùng', 'Đoan Hùng', null, '-230-Huyện Đoan Hùng-Đoan Hùng-', 'doanhung', null),
        (177, 42, '40', '427', 'Huyện Đô Lương', 'Huyện Đô Lương', 'Đô Lương', null, '-427-Huyện Đô Lương-Đô Lương-', 'doluong', null),
        (178, 28, '31', '308', 'Quận Đồ Sơn', 'Quận Đồ Sơn', 'Quận Đồ Sơn', null, '-308-Quận Đồ Sơn-Quận Đồ Sơn-', 'quandoson', null),
        (179, 24, '01', '017', 'Huyện Đông Anh', 'Huyện Đông Anh', 'Đông Anh', null, '-017-Huyện Đông Anh-Đông Anh-', 'donganh', null),
        (180, 48, '49', '505', 'Huyện Đông Giang', 'Huyện Đông Giang', 'Đông Giang', null, '-505-Huyện Đông Giang-Đông Giang-', 'donggiang', null),
        (181, 51, '45', '461', 'Thành phố Đông Hà', 'Thành phố Đông Hà', 'Đông Hà', null, '-461-Thành phố Đông Hà-Đông Hà-', 'dongha', null),
        (182, 5, '95', '960', 'Huyện Đông Hải', 'Huyện Đông Hải', 'Đông Hải', null, '-960-Huyện Đông Hải-Đông Hải-', 'donghai', null),
        (183, 46, '54', '564', 'Huyện Đông Hòa', 'Huyện Đông Hòa', 'Đông Hòa', null, '-564-Huyện Đông Hòa-Đông Hòa-', 'donghoa', null),
        (184, 55, '34', '340', 'Huyện Đông Hưng', 'Huyện Đông Hưng', 'Đông Hưng', null, '-340-Huyện Đông Hưng-Đông Hưng-', 'donghung', null),
        (185, 57, '38', '405', 'Huyện Đông Sơn', 'Huyện Đông Sơn', 'Đông Sơn', null, '-405-Huyện Đông Sơn-Đông Sơn-', 'dongson', null),
        (186, 50, '22', '205', 'Huyện Đông Triều', 'Huyện Đông Triều', 'Đông Triều', null, '-205-Huyện Đông Triều-Đông Triều-', 'dongtrieu', null),
        (187, 47, '44', '450', 'Thành phố Đồng Hới', 'Thành phố Đồng Hới', 'TP Đồng Hới', null, '-450-Thành Phố Đồng Hới-Đồng Hới-', 'tpdonghoi', null),
        (188, 56, '19', '169', 'Huyện Đồng Hỷ', 'Huyện Đồng Hỷ', 'Đồng Hỷ', null, '-169-Huyện Đồng Hỷ-Đồng Hỷ-', 'donghy', null),
        (189, 9, '70', '695', 'Huyện Đồng Phú', 'Huyện Đồng Phú', 'Đồng Phú', null, '-695-Huyện Đồng Phú-Đồng Phú-', 'dongphu', null),
        (190, 22, '02', '026', 'Huyện Đồng Văn', 'Huyện Đồng Văn', 'Đồng Văn', null, '-026-Huyện Đồng Văn-Đồng Văn-', 'dongvan', null),
        (191, 9, '70', '689', 'Thành phố Đồng Xoài', 'Thành phố Đồng Xoài', 'Đồng Xoài', null, '-689-Thành phố Đồng Xoài-Đồng Xoài-', 'dongxoai', null),
        (192, 46, '54', '558', 'Huyện Đồng Xuân', 'Huyện Đồng Xuân', 'Đồng Xuân', null, '-558-Huyện Đồng Xuân-Đồng Xuân-', 'dongxuan', null),
        (193, 24, '01', '006', 'Quận Đống Đa', 'Quận Đống Đa', 'Quận Đống Đa', null, '-006-Quận Đống Đa-Quận Đống Đa-', 'quandongda', null),
        (194, 37, '68', '677', 'Huyện Đơn Dương', 'Huyện Đơn Dương', 'Đơn Dương', null, '-677-Huyện Đơn Dương-Đơn Dương-', 'donduong', null),
        (195, 21, '64', '631', 'Huyện Đức Cơ', 'Huyện Đức Cơ', 'Đức Cơ', null, '-631-Huyện Đức Cơ-Đức Cơ-', 'ducco', null),
        (196, 40, '80', '802', 'Huyện Đức Hòa', 'Huyện Đức Hòa', 'Đức Hòa', null, '-802-Huyện Đức Hòa-Đức Hòa-', 'duchoa', null),
        (197, 40, '80', '801', 'Huyện Đức Huệ', 'Huyện Đức Huệ', 'Đức Huệ', null, '-801-Huyện Đức Huệ-Đức Huệ-', 'duchue', null),
        (198, 10, '60', '600', 'Huyện Đức Linh', 'Huyện Đức Linh', 'Đức Linh', null, '-600-Huyện Đức Linh-Đức Linh-', 'duclinh', null),
        (199, 49, '51', '534', 'Huyện Đức Phổ', 'Huyện Đức Phổ', 'Đức Phổ', null, '-534-Huyện Đức Phổ-Đức Phổ-', 'ducpho', null),
        (200, 26, '42', '440', 'Huyện Đức Thọ', 'Huyện Đức Thọ', 'Đức Thọ', null, '-440-Huyện Đức Thọ-Đức Thọ-', 'ductho', null),
        (201, 37, '68', '678', 'Huyện Đức Trọng', 'Huyện Đức Trọng', 'Đức Trọng', null, '-678-Huyện Đức Trọng-Đức Trọng-', 'ductrong', null),
        (202, 16, '66', '645', 'Huyện Ea H''leo', 'Huyện Ea H''leo', 'Ea H''leo', null, '-645-Huyện Ea H''leo-Ea H''leo-', 'eahleo', null),
        (203, 16, '66', '651', 'Huyện Ea Kar', 'Huyện Ea Kar', 'Ea Kar', null, '-651-Huyện Ea Kar-Ea Kar-', 'eakar', null),
        (204, 16, '66', '646', 'Huyện Ea Súp', 'Huyện Ea Súp', 'Ea Súp', null, '-646-Huyện Ea Súp-Ea Súp-', 'easup', null),
        (205, 6, '27', '263', 'Huyện Gia Bình', 'Huyện Gia Bình', 'Gia Bình', null, '-263-Huyện Gia Bình-Gia Bình-', 'giabinh', null),
        (206, 24, '01', '018', 'Huyện Gia Lâm', 'Huyện Gia Lâm', 'Gia Lâm', null, '-018-Huyện Gia Lâm-Gia Lâm-', 'gialam', null),
        (207, 27, '30', '297', 'Huyện Gia Lộc', 'Huyện Gia Lộc', 'Gia Lộc', null, '-297-Huyện Gia Lộc-Gia Lộc-', 'gialoc', null),
        (208, 17, '67', '660', 'Thị xã Gia Nghĩa', 'Thị xã Gia Nghĩa', 'Gia Nghĩa', null, '-660-Thị xã Gia Nghĩa-Gia Nghĩa-', 'gianghia', null),
        (209, 43, '37', '373', 'Huyện Gia Viễn', 'Huyện Gia Viễn', 'Gia Viễn', null, '-373-Huyện Gia Viễn-Gia Viễn-', 'giavien', null),
        (210, 5, '95', '959', 'Thị xã Giá Rai', 'Thị xã Giá Rai', 'Giá Rai', null, '-959-Thị xã Giá Rai-Giá Rai-', 'giarai', null),
        (211, 34, '91', '914', 'Huyện Giang Thành', 'Huyện Giang Thành', 'Giang Thành', null, '-914-Huyện Giang Thành-Giang Thành-', 'giangthanh', null),
        (212, 41, '36', '365', 'Huyện Giao Thủy', 'Huyện Giao Thủy', 'Giao Thủy', null, '-365-Huyện Giao Thủy-Giao Thủy-', 'giaothuy', null),
        (213, 51, '45', '466', 'Huyện Gio Linh', 'Huyện Gio Linh', 'Gio Linh', null, '-466-Huyện Gio Linh-Gio Linh-', 'giolinh', null),
        (214, 34, '91', '906', 'Huyện Giồng Riềng', 'Huyện Giồng Riềng', 'Giồng Riềng', null, '-906-Huyện Giồng Riềng-Giồng Riềng-', 'giongrieng', null),
        (215, 7, '83', '834', 'Huyện Giồng Trôm', 'Huyện Giồng Trôm', 'Giồng Trôm', null, '-834-Huyện Giồng Trôm-Giồng Trôm-', 'giongtrom', null),
        (216, 59, '82', '816', 'Thị xã Gò Công', 'Thị xã Gò Công', 'TX Gò Công', null, '-816-Thị xã Gò Công-Gò Công-', 'txgocong', null),
        (217, 59, '82', '824', 'Huyện Gò Công Đông', 'Huyện Gò Công Đông', 'Gò Công Đông', null, '-824-Huyện Gò Công Đông-Gò Công Đông-', 'gocongdong', null),
        (218, 59, '82', '823', 'Huyện Gò Công Tây', 'Huyện Gò Công Tây', 'Gò Công Tây', null, '-823-Huyện Gò Công Tây-Gò Công Tây-', 'gocongtay', null),
        (219, 54, '72', '710', 'Huyện Gò Dầu', 'Huyện Gò Dầu', 'Gò Dầu', null, '-710-Huyện Gò Dầu-Gò Dầu-', 'godau', null),
        (220, 34, '91', '907', 'Huyện Gò Quao', 'Huyện Gò Quao', 'Gò Quao', null, '-907-Huyện Gò Quao-Gò Quao-', 'goquao', null),
        (221, 30, '79', '764', 'Quận Gò Vấp', 'Quận Gò Vấp', 'Quận Gò Vấp', null, '-764-Quận Gò Vấp-Quận Gò Vấp-', 'quangovap', null),
        (222, 24, '01', '268', 'Quận Hà Đông', 'Quận Hà Đông', 'Quận Hà Đông', null, '-268-Quận Hà Đông-Quận Hà Đông-', 'quanhadong', null),
        (223, 22, '02', '024', 'Tp. Hà Giang', 'Tp. Hà Giang', 'TP Hà Giang', null, '-024-Thị xã Hà Giang-Hà Giang-Tp. Hà Giang-Tp Hà Giang-Thành phố Hà Giang-', 'tphagiang', null),
        (224, 14, '04', '045', 'Huyện Hà Quảng', 'Huyện Hà Quảng', 'Hà Quảng', null, '-045-Huyện Hà Quảng-Hà Quảng-', 'haquang', null),
        (225, 34, '91', '900', 'Thị xã Hà Tiên', 'Thị xã Hà Tiên', 'Hà Tiên', null, '-900-Thị xã Hà Tiên-Hà Tiên-', 'hatien', null),
        (226, 26, '42', '436', 'Thành phố Hà Tĩnh', 'Thành phố Hà Tĩnh', 'Hà Tĩnh', null, '-436-Thành phố Hà Tĩnh-Hà Tĩnh-', 'hatinh', null),
        (227, 57, '38', '392', 'Huyện Hà Trung', 'Huyện Hà Trung', 'Hà Trung', null, '-392-Huyện Hà Trung-Hà Trung-', 'hatrung', null),
        (228, 45, '25', '231', 'Huyện Hạ Hoà', 'Huyện Hạ Hoà', 'Hạ Hoà', null, '-231-Huyện Hạ Hoà-Hạ Hòa-', 'hahoa', null),
        (229, 14, '04', '048', 'Huyện Hạ Lang', 'Huyện Hạ Lang', 'Hạ Lang', null, '-048-Huyện Hạ Lang-Hạ Lang-', 'halang', null),
        (230, 50, '22', '193', 'Thành phố Hạ Long', 'Thành phố Hạ Long', 'Hạ Long', null, '-193-Thành phố Hạ Long-Hạ Long-', 'halong', null),
        (231, 24, '01', '007', 'Quận Hai Bà Trưng', 'Quận Hai Bà Trưng', 'Quận Hai Bà Trưng', null, '-007-Quận Hai Bà Trưng-Quận Hai Bà Trưng-', 'quanhaibatrung', null),
        (232, 28, '31', '306', 'Quận Hải An', 'Quận Hải An', 'Quận Hải An', null, '-306-Quận Hải An-Quận Hải An-', 'quanhaian', null),
        (233, 15, '48', '492', 'Quận Hải Châu', 'Quận Hải Châu', 'Hải Châu', null, '-492-Quận Hải Châu-Quận Hải Châu-', 'haichau', null),
        (234, 27, '30', '288', 'Thành phố Hải Dương', 'Thành phố Hải Dương', 'Hải Dương', null, '-288-Thành phố Hải Dương-Hải Dương-', 'haiduong', null),
        (235, 50, '22', '201', 'Huyện Hải Hà', 'Huyện Hải Hà', 'Hải Hà', null, '-201-Huyện Hải Hà-Hải Hà-', 'haiha', null),
        (236, 41, '36', '366', 'Huyện Hải Hậu', 'Huyện Hải Hậu', 'Hải Hậu', null, '-366-Huyện Hải Hậu-Hải Hậu-', 'haihau', null),
        (237, 51, '45', '470', 'Huyện Hải Lăng', 'Huyện Hải Lăng', 'Hải Lăng', null, '-470-Huyện Hải Lăng-Hải Lăng-', 'hailang', null),
        (238, 10, '60', '601', 'Huyện Hàm Tân', 'Huyện Hàm Tân', 'Hàm Tân', null, '-601-Huyện Hàm Tân-Hàm Tân-', 'hamtan', null),
        (239, 10, '60', '597', 'Huyện Hàm Thuận Bắc', 'Huyện Hàm Thuận Bắc', 'Hàm Thuận Bắc', null, '-597-Huyện Hàm Thuận Bắc-Hàm Thuận Bắc-', 'hamthuanbac', null),
        (240, 10, '60', '598', 'Huyện Hàm Thuận Nam', 'Huyện Hàm Thuận Nam', 'Hàm Thuận Nam', null, '-598-Huyện Hàm Thuận Nam-Hàm Thuận Nam-', 'hamthuannam', null),
        (241, 61, '08', '074', 'Huyện Hàm Yên', 'Huyện Hàm Yên', 'Hàm Yên', null, '-074-Huyện Hàm Yên-Hàm Yên-', 'hamyen', null),
        (242, 57, '38', '400', 'Huyện Hậu Lộc', 'Huyện Hậu Lộc', 'Hậu Lộc', null, '-400-Huyện Hậu Lộc-Hậu Lộc-', 'hauloc', null),
        (243, 48, '49', '512', 'Huyện Hiệp Đức', 'Huyện Hiệp Đức', 'Hiệp Đức', null, '-512-Huyện Hiệp Đức-Hiệp Đức-', 'hiepduc', null),
        (244, 3, '24', '223', 'Huyện Hiệp Hòa', 'Huyện Hiệp Hòa', 'Hiệp Hòa', null, '-223-Huyện Hiệp Hòa-Hiệp Hòa-', 'hiephoa', null),
        (245, 43, '37', '374', 'Huyện Hoa Lư', 'Huyện Hoa Lư', 'Hoa Lư', null, '-374-Huyện Hoa Lư-Hoa Lư-', 'hoalu', null),
        (246, 14, '04', '051', 'Huyện Hoà An', 'Huyện Hoà An', 'Hoà An', null, '-051-Huyện Hoà An-Hòa An-', 'hoaan', null),
        (247, 5, '95', '961', 'Huyện Hoà Bình', 'Huyện Hoà Bình', 'Hoà Bình', null, '-961-Huyện Hoà Bình-Hoà Bình-', 'hoabinh', null),
        (248, 31, '17', '148', 'Thành phố Hòa Bình', 'Thành phố Hòa Bình', 'TP.Hòa Bình', null, '-148-Thành phố Hòa Bình-Hoà Bình-', 'tphoabinh', null),
        (249, 54, '72', '709', 'Huyện Hòa Thành', 'Huyện Hòa Thành', 'Hòa Thành', null, '-709-Huyện Hòa Thành-Hòa Thành-', 'hoathanh', null),
        (250, 15, '48', '497', 'Huyện Hòa Vang', 'Huyện Hòa Vang', 'Hòa Vang', null, '-497-Huyện Hòa Vang-Hoà Vang-', 'hoavang', null),
        (251, 11, '52', '544', 'Huyện Hoài Ân', 'Huyện Hoài Ân', 'Hoài Ân', null, '-544-Huyện Hoài Ân-Hoài Ân-', 'hoaian', null),
        (252, 24, '01', '274', 'Huyện Hoài Đức', 'Huyện Hoài Đức', 'Hoài Đức', null, '-274-Huyện Hoài Đức-Hoài Đức-', 'hoaiduc', null),
        (253, 11, '52', '543', 'Huyện Hoài Nhơn', 'Huyện Hoài Nhơn', 'Hoài Nhơn', null, '-543-Huyện Hoài Nhơn-Hoài Nhơn-', 'hoainhon', null),
        (254, 24, '01', '002', 'Quận Hoàn Kiếm', 'Quận Hoàn Kiếm', 'Quận Hoàn Kiếm', null, '-002-Quận Hoàn Kiếm-Quận Hoàn Kiếm-', 'quanhoankiem', null),
        (255, 24, '01', '008', 'Quận Hoàng Mai', 'Quận Hoàng Mai', 'Quận Hoàng Mai', null, '-008-Quận Hoàng Mai-Quận Hoàng Mai-', 'quanhoangmai', null),
        (256, 15, '48', '498', 'Huyện Hoàng Sa', 'Huyện Hoàng Sa', 'Hoàng Sa', null, '-498-Huyện Hoàng Sa-Hoàng Sa-', 'hoangsa', null),
        (257, 22, '02', '032', 'Huyện Hoàng Su Phì', 'Huyện Hoàng Su Phì', 'Hoàng Su Phì', null, '-032-Huyện Hoàng Su Phì-Hoàng Su Phì-', 'hoangsuphi', null),
        (258, 50, '22', '204', 'Huyện Hoành Bồ', 'Huyện Hoành Bồ', 'Hoành Bồ', null, '-204-Huyện Hoành Bồ-Hoành Bồ-', 'hoanhbo', null),
        (259, 57, '38', '399', 'Huyện Hoằng Hóa', 'Huyện Hoằng Hóa', 'Hoằng Hóa', null, '-399-Huyện Hoằng Hóa-Hoằng Hóa-', 'hoanghoa', null),
        (260, 30, '79', '784', 'Huyện Hóc Môn', 'Huyện Hóc Môn', 'Hóc Môn', null, '-784-Huyện Hóc Môn-Hóc Môn-', 'hocmon', null),
        (261, 34, '91', '903', 'Huyện Hòn Đất', 'Huyện Hòn Đất', 'Hòn Đất', null, '-903-Huyện Hòn Đất-Hòn Đất-', 'hondat', null),
        (262, 9, '70', '694', 'Huyện Hớn Quản', 'Huyện Hớn Quản', 'Hớn Quản', null, '-694-Huyện Hớn Quản-Hớn Quản-', 'honquan', null),
        (263, 48, '49', '503', 'Thành phố Hội An', 'Thành phố Hội An', 'Hội An', null, '-503-Thành phố Hội An-Hội An-', 'hoian', null),
        (264, 28, '31', '303', 'Quận Hồng Bàng', 'Quận Hồng Bàng', 'Quận Hồng Bàng', null, '-303-Quận Hồng Bàng-Quận Hồng Bàng-', 'quanhongbang', null),
        (265, 5, '95', '956', 'Huyện Hồng Dân', 'Huyện Hồng Dân', 'Hồng Dân', null, '-956-Huyện Hồng Dân-Hồng Dân-', 'hongdan', null),
        (266, 26, '42', '437', 'Thị xã Hồng Lĩnh', 'Thị xã Hồng Lĩnh', 'Hồng Lĩnh', null, '-437-Thị xã Hồng Lĩnh-Hồng Lĩnh-', 'honglinh', null),
        (267, 20, '87', '870', 'Huyện Hồng Ngự', 'Huyện Hồng Ngự', 'Hồng Ngự', null, '-866-Huyện Hồng Ngự-Hồng Ngự-', 'hongngu', null),
        (268, 20, '87', '868', 'Thị xã Hồng Ngự', 'Thị xã Hồng Ngự', 'TX Hồng Ngự', null, '-868-Thị xã Hồng Ngự-Hồng Ngự-', 'txhongngu', null),
        (269, 58, '46', '474', 'Thành phố Huế', 'Thành phố Huế', 'Huế', null, '-474-Thành phố Huế-Huế-', 'hue', null),
        (270, 55, '34', '339', 'Huyện Hưng Hà', 'Huyện Hưng Hà', 'Hưng Hà', null, '-339-Huyện Hưng Hà-Hưng Hà-', 'hungha', null),
        (271, 42, '40', '431', 'Huyện Hưng Nguyên', 'Huyện Hưng Nguyên', 'Hưng Nguyên', null, '-431-Huyện Hưng Nguyên-Hưng Nguyên-', 'hungnguyen', null),
        (272, 32, '33', '323', 'Thành phố Hưng Yên', 'Thành phố Hưng Yên', 'Hưng Yên', null, '-323-Thành phố Hưng Yên-Hưng Yên-', 'hungyen', null),
        (273, 26, '42', '444', 'Huyện Hương Khê', 'Huyện Hương Khê', 'Hương Khê', null, '-444-Huyện Hương Khê-Hương Khê-', 'huongkhe', null),
        (274, 26, '42', '439', 'Huyện Hương Sơn', 'Huyện Hương Sơn', 'Hương Sơn', null, '-439-Huyện Hương Sơn-Hương Sơn-', 'huongson', null),
        (275, 58, '46', '479', 'Thị xã Hương Thủy', 'Thị xã Hương Thủy', 'Hương Thủy', null, '-479-Thị xã Hương Thủy-Hương Thủy-', 'huongthuy', null),
        (276, 58, '46', '480', 'Thị xã Hương Trà', 'Thị xã Hương Trà', 'Hương Trà', null, '-480-Thị xã Hương Trà-Hương Trà-', 'huongtra', null),
        (277, 51, '45', '465', 'Huyện Hướng Hóa', 'Huyện Hướng Hóa', 'Hướng Hóa', null, '-465-Huyện Hướng Hóa-Hướng Hóa-', 'huonghoa', null),
        (278, 38, '20', '186', 'Huyện Hữu Lũng', 'Huyện Hữu Lũng', 'Hữu Lũng', null, '-186-Huyện Hữu Lũng-Hữu Lũng-', 'huulung', null),
        (279, 21, '64', '628', 'Huyện Ia Grai', 'Huyện Ia Grai', 'Ia Grai', null, '-628-Huyện Ia Grai-Ia Grai-', 'iagrai', null),
        (280, 21, '64', '635', 'Huyện Ia Pa', 'Huyện Ia Pa', 'Ia Pa', null, '-635-Huyện Ia Pa-Ia Pa-', 'iapa', null),
        (281, 21, '64', '625', 'Huyện KBang', 'Huyện KBang', 'KBang', null, '-625-Huyện KBang-KBang-', 'kbang', null),
        (282, 52, '94', '943', 'Huyện Kế Sách', 'Huyện Kế Sách', 'Kế Sách', null, '-943-Huyện Kế Sách-Kế Sách-', 'kesach', null),
        (283, 33, '56', '575', 'Huyện Khánh Sơn', 'Huyện Khánh Sơn', 'Khánh Sơn', null, '-575-Huyện Khánh Sơn-Khánh Sơn-', 'khanhson', null),
        (284, 33, '56', '573', 'Huyện Khánh Vĩnh', 'Huyện Khánh Vĩnh', 'Khánh Vĩnh', null, '-573-Huyện Khánh Vĩnh-Khánh Vĩnh-', 'khanhvinh', null),
        (285, 32, '33', '330', 'Huyện Khoái Châu', 'Huyện Khoái Châu', 'Khoái Châu', null, '-330-Huyện Khoái Châu-Khoái Châu-', 'khoaichau', null),
        (286, 34, '91', '912', 'Huyện Kiên Hải', 'Huyện Kiên Hải', 'Kiên Hải', null, '-912-Huyện Kiên Hải-Kiên Hải-', 'kienhai', null),
        (287, 34, '91', '902', 'Huyện Kiên Lương', 'Huyện Kiên Lương', 'Kiên Lương', null, '-902-Huyện Kiên Lương-Kiên Lương-', 'kienluong', null),
        (288, 28, '31', '307', 'Quận Kiến An', 'Quận Kiến An', 'Quận Kiến An', null, '-307-Quận Kiến An-Quận Kiến An-', 'quankienan', null),
        (289, 28, '31', '314', 'Huyện Kiến Thuỵ', 'Huyện Kiến Thuỵ', 'Kiến Thuỵ', null, '-314-Huyện Kiến Thuỵ-Kiến Thụy-', 'kienthuy', null),
        (290, 55, '34', '343', 'Huyện Kiến Xương', 'Huyện Kiến Xương', 'Kiến Xương', null, '-343-Huyện Kiến Xương-Kiến Xương-', 'kienxuong', null),
        (291, 23, '35', '350', 'Huyện Kim Bảng', 'Huyện Kim Bảng', 'Kim Bảng', null, '-350-Huyện Kim Bảng-Kim Bảng-', 'kimbang', null),
        (292, 31, '17', '153', 'Huyện Kim Bôi', 'Huyện Kim Bôi', 'Kim Bôi', null, '-153-Huyện Kim Bôi-Kim Bôi-', 'kimboi', null),
        (293, 32, '33', '331', 'Huyện Kim Động', 'Huyện Kim Động', 'Kim Động', null, '-331-Huyện Kim Động-Kim Động-', 'kimdong', null),
        (294, 43, '37', '376', 'Huyện Kim Sơn', 'Huyện Kim Sơn', 'Kim Sơn', null, '-376-Huyện Kim Sơn-Kim Sơn-', 'kimson', null),
        (295, 27, '30', '293', 'Huyện Kim Thành', 'Huyện Kim Thành', 'Kim Thành', null, '-293-Huyện Kim Thành-Kim Thành-', 'kimthanh', null),
        (296, 27, '30', '292', 'Huyện Kinh Môn', 'Huyện Kinh Môn', 'Kinh Môn', null, '-292-Huyện Kinh Môn-Kinh Môn-', 'kinhmon', null),
        (297, 35, '62', '613', 'Huyện Kon Plông', 'Huyện Kon Plông', 'Kon Plông', null, '-613-Huyện Kon Plông-Kon Plông-', 'konplong', null),
        (298, 35, '62', '614', 'Huyện Kon Rẫy', 'Huyện Kon Rẫy', 'Kon Rẫy', null, '-614-Huyện Kon Rẫy-Kon Rẫy-', 'konray', null),
        (299, 35, '62', '608', 'Thành phố Kon Tum', 'Thành phố Kon Tum', 'Kon Tum', null, '-608-Thành phố Kon Tum-Kon Tum-', 'kontum', null),
        (300, 21, '64', '630', 'Huyện Kông Chro', 'Huyện Kông Chro', 'Kông Chro', null, '-630-Huyện Kông Chro-Kông Chro-', 'kongchro', null),
        (301, 16, '66', '655', 'Huyện Krông Ana', 'Huyện Krông Ana', 'Krông Ana', null, '-655-Huyện Krông Ana-Krông Ana-', 'krongana', null),
        (302, 16, '66', '653', 'Huyện Krông Bông', 'Huyện Krông Bông', 'Krông Bông', null, '-653-Huyện Krông Bông-Krông Bông-', 'krongbong', null),
        (303, 16, '66', '649', 'Huyện Krông Búk', 'Huyện Krông Búk', 'Krông Búk', null, '-649-Huyện Krông Búk-Krông Búk-', 'krongbuk', null),
        (304, 16, '66', '650', 'Huyện Krông Năng', 'Huyện Krông Năng', 'Krông Năng', null, '-650-Huyện Krông Năng-Krông Năng-', 'krongnang', null),
        (305, 17, '67', '664', 'Huyện Krông Nô', 'Huyện Krông Nô', 'Krông Nô', null, '-664-Huyện Krông Nô-Krông Nô-', 'krongno', null),
        (306, 21, '64', '637', 'Huyện Krông Pa', 'Huyện Krông Pa', 'Krông Pa', null, '-637-Huyện Krông Pa-Krông Pa-', 'krongpa', null),
        (309, 31, '17', '151', 'Huyện Kỳ Sơn', 'Huyện Kỳ Sơn', 'Kỳ Sơn', null, '-151-Huyện Kỳ Sơn-Kỳ Sơn-', 'kyson', null),
        (310, 42, '40', '417', 'Huyện Kỳ Sơn', 'Huyện Kỳ Sơn', 'Kỳ Sơn', null, '-417-Huyện Kỳ Sơn-Kỳ Sơn-', 'kyson', null),
        (311, 10, '60', '594', 'Thị xã La Gi', 'Thị xã La Gi', 'La Gi', null, '-594-Thị xã La Gi-La Gi-', 'lagi', null),
        (312, 37, '68', '675', 'Huyện Lạc Dương', 'Huyện Lạc Dương', 'Lạc Dương', null, '-675-Huyện Lạc Dương-Lạc Dương-', 'lacduong', null),
        (313, 31, '17', '157', 'Huyện Lạc Sơn', 'Huyện Lạc Sơn', 'Lạc Sơn', null, '-157-Huyện Lạc Sơn-Lạc Sơn-', 'lacson', null),
        (314, 31, '17', '159', 'Huyện Lạc Thủy', 'Huyện Lạc Thủy', 'Lạc Thủy', null, '-159-Huyện Lạc Thủy-Lạc Thủy-', 'lacthuy', null),
        (315, 36, '12', '105', 'Thị xã Lai Châu', 'Thị xã Lai Châu', 'Lai Châu', null, '-105-Thị xã Lai Châu-Lai Châu-', 'laichau', null),
        (316, 20, '87', '876', 'Huyện Lai Vung', 'Huyện Lai Vung', 'Lai Vung', null, '-876-Huyện Lai Vung-Lai Vung-', 'laivung', null),
        (317, 57, '38', '388', 'Huyện Lang Chánh', 'Huyện Lang Chánh', 'Lang Chánh', null, '-388-Huyện Lang Chánh-Lang Chánh-', 'langchanh', null),
        (318, 3, '24', '217', 'Huyện Lạng Giang', 'Huyện Lạng Giang', 'Lạng Giang', null, '-217-Huyện Lạng Giang-Lạng Giang-', 'langgiang', null),
        (319, 38, '20', '178', 'Thành phố Lạng Sơn', 'Thành phố Lạng Sơn', 'Lạng Sơn', null, '-178-Thành phố Lạng Sơn-Lạng Sơn-', 'langson', null),
        (320, 39, '10', '080', 'Thành phố Lào Cai', 'Thành phố Lào Cai', 'Lào Cai', null, '-080-Thành phố Lào Cai-Lào Cai-', 'laocai', null),
        (321, 16, '66', '656', 'Huyện Lắk', 'Huyện Lắk', 'Lắk', null, '-656-Huyện Lắk-Lăk-', 'lak', null),
        (322, 61, '08', '071', 'Huyện Lâm Bình', 'Huyện Lâm Bình', 'Lâm Bình', null, '-071-Huyện Lâm Bình-Lâm Bình-', 'lambinh', null),
        (323, 37, '68', '676', 'Huyện Lâm Hà', 'Huyện Lâm Hà', 'Lâm Hà', null, '-676-Huyện Lâm Hà-Lâm Hà-', 'lamha', null),
        (324, 45, '25', '237', 'Huyện Lâm Thao', 'Huyện Lâm Thao', 'Lâm Thao', null, '-237-Huyện Lâm Thao-Lâm Thao-', 'lamthao', null),
        (325, 20, '87', '875', 'Huyện Lấp Vò', 'Huyện Lấp Vò', 'Lấp Vò', null, '-875-Huyện Lấp Vò-Lấp Vò-', 'lapvo', null),
        (326, 63, '26', '246', 'Huyện Lập Thạch', 'Huyện Lập Thạch', 'Lập Thạch', null, '-246-Huyện Lập Thạch-Lập Thạch-', 'lapthach', null),
        (327, 28, '31', '305', 'Quận Lê Chân', 'Quận Lê Chân', 'Quận Lê Chân', null, '-305-Quận Lê Chân-Quận Lê Chân-', 'quanlechan', null),
        (328, 47, '44', '457', 'Huyện Lệ Thủy', 'Huyện Lệ Thủy', 'Lệ Thủy', null, '-457-Huyện Lệ Thủy-Lệ Thủy-', 'lethuy', null),
        (329, 15, '48', '490', 'Quận Liên Chiểu', 'Quận Liên Chiểu', 'Liên Chiểu', null, '-490-Quận Liên Chiểu-Quận Liên Chiểu-', 'lienchieu', null),
        (330, 24, '01', '004', 'Quận Long Biên', 'Quận Long Biên', 'Quận Long Biên', null, '-004-Quận Long Biên-Quận Long Biên-', 'quanlongbien', null),
        (331, 2, '77', '752', 'Huyện Long Điền', 'Huyện Long Điền', 'Long Điền', null, '-752-Huyện Long Điền-Long Điền-', 'longdien', null),
        (332, 62, '86', '857', 'Huyện Long Hồ', 'Huyện Long Hồ', 'Long Hồ', null, '-857-Huyện Long Hồ-Long Hồ-', 'longho', null),
        (333, 19, '75', '732', 'Thị xã Long Khánh', 'Thị xã Long Khánh', 'TX Long Khánh', null, '-732-Thị xã Long Khánh-Long Khánh-', 'txlongkhanh', null),
        (335, 52, '94', '946', 'Huyện Long Phú', 'Huyện Long Phú', 'Long Phú', null, '-946-Huyện Long Phú-Long Phú-', 'longphu', null),
        (336, 19, '75', '740', 'Huyện Long Thành', 'Huyện Long Thành', 'Long Thành', null, '-740-Huyện Long Thành-Long Thành-', 'longthanh', null),
        (337, 1, '89', '883', 'Thành phố Long Xuyên', 'Thành phố Long Xuyên', 'Long Xuyên', null, '-883-Thành phố Long Xuyên-Long Xuyên-', 'longxuyen', null),
        (338, 38, '20', '188', 'Huyện Lộc Bình', 'Huyện Lộc Bình', 'Lộc Bình', null, '-188-Huyện Lộc Bình-Lộc Bình-', 'locbinh', null),
        (339, 26, '42', '448', 'Huyện Lộc Hà', 'Huyện Lộc Hà', 'Lộc Hà', null, '-448-Huyện Lộc Hà-Lộc Hà-', 'locha', null),
        (340, 9, '70', '692', 'Huyện Lộc Ninh', 'Huyện Lộc Ninh', 'Lộc Ninh', null, '-692-Huyện Lộc Ninh-Lộc Ninh-', 'locninh', null),
        (341, 3, '24', '218', 'Huyện Lục Nam', 'Huyện Lục Nam', 'Lục Nam', null, '-218-Huyện Lục Nam-Lục Nam-', 'lucnam', null),
        (342, 3, '24', '219', 'Huyện Lục Ngạn', 'Huyện Lục Ngạn', 'Lục Ngạn', null, '-219-Huyện Lục Ngạn-Lục Ngạn-', 'lucngan', null),
        (343, 64, '15', '135', 'Huyện Lục Yên', 'Huyện Lục Yên', 'Lục Yên', null, '-135-Huyện Lục Yên-Lục Yên-', 'lucyen', null),
        (344, 31, '17', '152', 'Huyện Lương Sơn', 'Huyện Lương Sơn', 'Lương Sơn', null, '-152-Huyện Lương Sơn-Lương Sơn-', 'luongson', null),
        (345, 6, '27', '264', 'Huyện Lương Tài', 'Huyện Lương Tài', 'Lương Tài', null, '-264-Huyện Lương Tài-Lương Tài-', 'luongtai', null),
        (346, 23, '35', '353', 'Huyện Lý Nhân', 'Huyện Lý Nhân', 'Lý Nhân', null, '-353-Huyện Lý Nhân-Lý Nhân-', 'lynhan', null),
        (347, 49, '51', '536', 'Huyện Lý Sơn', 'Huyện Lý Sơn', 'Lý Sơn', null, '-536-Huyện Lý Sơn-Lý Sơn-', 'lyson', null),
        (348, 31, '17', '156', 'Huyện Mai Châu', 'Huyện Mai Châu', 'Mai Châu', null, '-156-Huyện Mai Châu-Mai Châu-', 'maichau', null),
        (349, 53, '14', '125', 'Huyện Mai Sơn', 'Huyện Mai Sơn', 'Mai Sơn', null, '-125-Huyện Mai Sơn-Mai Sơn-', 'maison', null),
        (350, 62, '86', '858', 'Huyện Mang Thít', 'Huyện Mang Thít', 'Mang Thít', null, '-858-Huyện Mang Thít-Mang Thít-', 'mangthit', null),
        (351, 21, '64', '629', 'Huyện Mang Yang', 'Huyện Mang Yang', 'Mang Yang', null, '-629-Huyện Mang Yang-Mang Yang-', 'mangyang', null),
        (352, 16, '66', '652', 'Huyện M''Đrắk', 'Huyện M''Đrắk', 'M''Đrắk', null, '-652-Huyện M''Đrắk-M''Đrăk-', 'mdrak', null),
        (353, 22, '02', '027', 'Huyện Mèo Vạc', 'Huyện Mèo Vạc', 'Mèo Vạc', null, '-027-Huyện Mèo Vạc-Mèo Vạc-', 'meovac', null),
        (354, 24, '01', '250', 'Huyện Mê Linh', 'Huyện Mê Linh', 'Mê Linh', null, '-250-Huyện Mê Linh-Mê Linh-', 'melinh', null),
        (355, 47, '44', '452', 'Huyện Minh Hóa', 'Huyện Minh Hóa', 'Minh Hóa', null, '-452-Huyện Minh Hóa-Minh Hóa-', 'minhhoa', null),
        (356, 49, '51', '531', 'Huyện Minh Long', 'Huyện Minh Long', 'Minh Long', null, '-531-Huyện Minh Long-Minh Long-', 'minhlong', null),
        (357, 7, '83', '838', 'Huyện Mỏ Cày Bắc', 'Huyện Mỏ Cày Bắc', 'Mỏ Cày Bắc', null, '-838-Huyện Mỏ Cày Bắc-Mỏ Cày Bắc-', 'mocaybac', null),
        (358, 7, '83', '833', 'Huyện Mỏ Cày Nam', 'Huyện Mỏ Cày Nam', 'Mỏ Cày Nam', null, '-833-Huyện Mỏ Cày Nam-Mỏ Cày Nam-', 'mocaynam', null),
        (359, 50, '22', '194', 'Thành phố Móng Cái', 'Thành phố Móng Cái', 'Móng Cái', null, '-194-Thành phố Móng Cái-Móng Cái-', 'mongcai', null),
        (360, 49, '51', '533', 'Huyện Mộ Đức', 'Huyện Mộ Đức', 'Mộ Đức', null, '-533-Huyện Mộ Đức-Mộ Đức-', 'moduc', null),
        (361, 53, '14', '123', 'Huyện Mộc Châu', 'Huyện Mộc Châu', 'Mộc Châu', null, '-123-Huyện Mộc Châu-Mộc Châu-', 'mocchau', null),
        (362, 40, '80', '798', 'Huyện Mộc Hóa', 'Huyện Mộc Hóa', 'Mộc Hóa', null, '-798-Huyện Mộc Hóa-Mộc Hóa-', 'mochoa', null),
        (363, 64, '15', '137', 'Huyện Mù Căng Chải', 'Huyện Mù Căng Chải', 'Mù Căng Chải', null, '-137-Huyện Mù Căng Chải-Mù Căng Chải-', 'mucangchai', null),
        (364, 18, '11', '102', 'Huyện Mường Ảng', 'Huyện Mường Ảng', 'Mường Ảng', null, '-102-Huyện Mường Ảng-Mường Ảng-', 'muongang', null),
        (365, 18, '11', '097', 'Huyện Mường Chà', 'Huyện Mường Chà', 'Mường Chà', null, '-097-Huyện Mường Chà-Mường Chà-', 'muongcha', null),
        (366, 39, '10', '083', 'Huyện Mường Khương', 'Huyện Mường Khương', 'Mường Khương', null, '-083-Huyện Mường Khương-Mường Khương-', 'muongkhuong', null),
        (367, 53, '14', '120', 'Huyện Mường La', 'Huyện Mường La', 'Mường La', null, '-120-Huyện Mường La-Mường La-', 'muongla', null),
        (368, 57, '38', '384', 'Huyện Mường Lát', 'Huyện Mường Lát', 'Mường Lát', null, '-384-Huyện Mường Lát-Mường Lát-', 'muonglat', null),
        (369, 18, '11', '095', 'Thị Xã Mường Lay', 'Thị Xã Mường Lay', 'TX Mường Lay', null, '-095-Thị Xã Mường Lay-Mường Lay-', 'txmuonglay', null),
        (370, 18, '11', '096', 'Huyện Mường Nhé', 'Huyện Mường Nhé', 'Mường Nhé', null, '-096-Huyện Mường Nhé-Mường Nhé-', 'muongnhe', null),
        (371, 36, '12', '107', 'Huyện Mường Tè', 'Huyện Mường Tè', 'Mường Tè', null, '-107-Huyện Mường Tè-Mường Tè-', 'muongte', null),
        (372, 24, '01', '282', 'Huyện Mỹ Đức', 'Huyện Mỹ Đức', 'Mỹ Đức', null, '-282-Huyện Mỹ Đức-Mỹ Đức-', 'myduc', null),
        (373, 32, '33', '328', 'Huyện Mỹ Hào', 'Huyện Mỹ Hào', 'Mỹ Hào', null, '-328-Huyện Mỹ Hào-Mỹ Hào-', 'myhao', null),
        (374, 41, '36', '358', 'Huyện Mỹ Lộc', 'Huyện Mỹ Lộc', 'Mỹ Lộc', null, '-358-Huyện Mỹ Lộc-Mỹ Lộc-', 'myloc', null),
        (375, 59, '82', '815', 'Thành phố Mỹ Tho', 'Thành phố Mỹ Tho', 'Mỹ Tho', null, '-815-Thành phố Mỹ Tho-Mỹ Tho-', 'mytho', null),
        (376, 52, '94', '944', 'Huyện Mỹ Tú', 'Huyện Mỹ Tú', 'Mỹ Tú', null, '-944-Huyện Mỹ Tú-Mỹ Tú-', 'mytu', null),
        (377, 52, '94', '947', 'Huyện Mỹ Xuyên', 'Huyện Mỹ Xuyên', 'Mỹ Xuyên', null, '-947-Huyện Mỹ Xuyên-Mỹ Xuyên-', 'myxuyen', null),
        (378, 61, '08', '072', 'Huyện Nà Hang', 'Huyện Nà Hang', 'Nà Hang', null, '-072-Huyện Nà Hang-Na Hang-', 'nahang', null),
        (379, 4, '06', '066', 'Huyện Na Rì', 'Huyện Na Rì', 'Na Rì', null, '-066-Huyện Na Rì-Na Rì-', 'nari', null),
        (380, 42, '40', '430', 'Huyện Nam Đàn', 'Huyện Nam Đàn', 'Nam Đàn', null, '-430-Huyện Nam Đàn-Nam Đàn-', 'namdan', null),
        (381, 41, '36', '356', 'Thành phố Nam Định', 'Thành phố Nam Định', 'Nam Định', null, '-356-Thành phố Nam Định-Nam Định-', 'namdinh', null),
        (382, 58, '46', '483', 'Huyện Nam Đông', 'Huyện Nam Đông', 'Nam Đông', null, '-483-Huyện Nam Đông-Nam Đông-', 'namdong', null),
        (383, 48, '49', '510', 'Huyện Nam Giang', 'Huyện Nam Giang', 'Nam Giang', null, '-510-Huyện Nam Giang-Nam Giang-', 'namgiang', null),
        (384, 27, '30', '291', 'Huyện Nam Sách', 'Huyện Nam Sách', 'Nam Sách', null, '-291-Huyện Nam Sách-Nam Sách-', 'namsach', null),
        (385, 48, '49', '516', 'Huyện Nam Trà My', 'Huyện Nam Trà My', 'Nam Trà My', null, '-516-Huyện Nam Trà My-Nam Trà My-', 'namtramy', null),
        (386, 41, '36', '362', 'Huyện Nam Trực', 'Huyện Nam Trực', 'Nam Trực', null, '-362-Huyện Nam Trực-Nam Trực-', 'namtruc', null),
        (387, 12, '96', '971', 'Huyện Năm Căn', 'Huyện Năm Căn', 'Năm Căn', null, '-971-Huyện Năm Căn-Năm Căn-', 'namcan', null),
        (388, 57, '38', '401', 'Huyện Nga Sơn', 'Huyện Nga Sơn', 'Nga Sơn', null, '-401-Huyện Nga Sơn-Nga Sơn-', 'ngason', null),
        (389, 29, '93', '931', 'Thị xã Ngã Bảy', 'Thị xã Ngã Bảy', 'Ngã Bảy', null, '-931-Thị xã Ngã Bảy-Ngã Bảy-', 'ngabay', null),
        (390, 52, '94', '948', 'Thị xã Ngã Năm', 'Thị xã Ngã Năm', 'Ngã Năm', null, '-948-Thị xã Ngã Năm-Ngã Năm-', 'nganam', null),
        (391, 4, '06', '062', 'Huyện Ngân Sơn', 'Huyện Ngân Sơn', 'Ngân Sơn', null, '-062-Huyện Ngân Sơn-Ngân Sơn-', 'nganson', null),
        (392, 42, '40', '429', 'Huyện Nghi Lộc', 'Huyện Nghi Lộc', 'Nghi Lộc', null, '-429-Huyện Nghi Lộc-Nghi Lộc-', 'nghiloc', null),
        (393, 26, '42', '442', 'Huyện Nghi Xuân', 'Huyện Nghi Xuân', 'Nghi Xuân', null, '-442-Huyện Nghi Xuân-Nghi Xuân-', 'nghixuan', null),
        (394, 42, '40', '419', 'Huyện Nghĩa Đàn', 'Huyện Nghĩa Đàn', 'Nghĩa Đàn', null, '-419-Huyện Nghĩa Đàn-Nghĩa Đàn-', 'nghiadan', null),
        (395, 49, '51', '532', 'Huyện Nghĩa Hành', 'Huyện Nghĩa Hành', 'Nghĩa Hành', null, '-532-Huyện Nghĩa Hành-Nghĩa Hành-', 'nghiahanh', null),
        (396, 41, '36', '361', 'Huyện Nghĩa Hưng', 'Huyện Nghĩa Hưng', 'Nghĩa Hưng', null, '-361-Huyện Nghĩa Hưng-Nghĩa Hưng-', 'nghiahung', null),
        (397, 64, '15', '133', 'Thị xã Nghĩa Lộ', 'Thị xã Nghĩa Lộ', 'Nghĩa Lộ', null, '-133-Thị xã Nghĩa Lộ-Nghĩa Lộ-', 'nghialo', null),
        (398, 12, '96', '973', 'Huyện Ngọc Hiển', 'Huyện Ngọc Hiển', 'Ngọc Hiển', null, '-973-Huyện Ngọc Hiển-Ngọc Hiển-', 'ngochien', null),
        (399, 35, '62', '611', 'Huyện Ngọc Hồi', 'Huyện Ngọc Hồi', 'Ngọc Hồi', null, '-611-Huyện Ngọc Hồi-Ngọc Hồi-', 'ngochoi', null),
        (400, 57, '38', '389', 'Huyện Ngọc Lặc', 'Huyện Ngọc Lặc', 'Ngọc Lặc', null, '-389-Huyện Ngọc Lặc-Ngọc Lặc-', 'ngoclac', null),
        (401, 28, '31', '304', 'Quận Ngô Quyền', 'Quận Ngô Quyền', 'Quận Ngô Quyền', null, '-304-Quận Ngô Quyền-Quận Ngô Quyền-', 'quanngoquyen', null),
        (402, 15, '48', '494', 'Quận Ngũ Hành Sơn', 'Quận Ngũ Hành Sơn', 'Ngũ Hành Sơn', null, '-494-Quận Ngũ Hành Sơn-Quận Ngũ Hành Sơn-', 'nguhanhson', null),
        (403, 14, '04', '052', 'Huyện Nguyên Bình', 'Huyện Nguyên Bình', 'Nguyên Bình', null, '-052-Huyện Nguyên Bình-Nguyên Bình-', 'nguyenbinh', null),
        (404, 33, '56', '568', 'Thành phố Nha Trang', 'Thành phố Nha Trang', 'Nha Trang', null, '-568-Thành phố Nha Trang-Nha Trang-', 'nhatrang', null),
        (405, 30, '79', '786', 'Huyện Nhà Bè', 'Huyện Nhà Bè', 'Nhà Bè', null, '-786-Huyện Nhà Bè-Nhà Bè-', 'nhabe', null),
        (406, 43, '37', '372', 'Huyện Nho Quan', 'Huyện Nho Quan', 'Nho Quan', null, '-372-Huyện Nho Quan-Nho Quan-', 'nhoquan', null),
        (407, 19, '75', '742', 'Huyện Nhơn Trạch', 'Huyện Nhơn Trạch', 'Nhơn Trạch', null, '-742-Huyện Nhơn Trạch-Nhơn Trạch-', 'nhontrach', null),
        (408, 57, '38', '403', 'Huyện Như Thanh', 'Huyện Như Thanh', 'Như Thanh', null, '-403-Huyện Như Thanh-Như Thanh-', 'nhuthanh', null),
        (409, 57, '38', '402', 'Huyện Như Xuân', 'Huyện Như Xuân', 'Như Xuân', null, '-402-Huyện Như Xuân-Như Xuân-', 'nhuxuan', null),
        (410, 43, '37', '369', 'Thành phố Ninh Bình', 'Thành phố Ninh Bình', 'Ninh Bình', null, '-369-Thành phố Ninh Bình-Ninh Bình-', 'ninhbinh', null),
        (411, 27, '30', '299', 'Huyện Ninh Giang', 'Huyện Ninh Giang', 'Ninh Giang', null, '-299-Huyện Ninh Giang-Ninh Giang-', 'ninhgiang', null),
        (412, 44, '58', '586', 'Huyện Ninh Hải', 'Huyện Ninh Hải', 'Ninh Hải', null, '-586-Huyện Ninh Hải-Ninh Hải-', 'ninhhai', null),
        (413, 33, '56', '572', 'Thị xã Ninh Hòa', 'Thị xã Ninh Hòa', 'Ninh Hòa', null, '-572-Thị xã Ninh Hòa-Ninh Hòa-', 'ninhhoa', null),
        (414, 13, '92', '916', 'Quận Ninh Kiều', 'Quận Ninh Kiều', 'Quận Ninh Kiều', null, '-916-Quận Ninh Kiều-Quận Ninh Kiều-', 'quanninhkieu', null),
        (415, 44, '58', '587', 'Huyện Ninh Phước', 'Huyện Ninh Phước', 'Ninh Phước', null, '-587-Huyện Ninh Phước-Ninh Phước-', 'ninhphuoc', null),
        (416, 44, '58', '585', 'Huyện Ninh Sơn', 'Huyện Ninh Sơn', 'Ninh Sơn', null, '-585-Huyện Ninh Sơn-Ninh Sơn-', 'ninhson', null),
        (417, 57, '38', '404', 'Huyện Nông Cống', 'Huyện Nông Cống', 'Nông Cống', null, '-404-Huyện Nông Cống-Nông Cống-', 'nongcong', null),
        (418, 48, '49', '519', 'Huyện Nông Sơn', 'Huyện Nông Sơn', 'Nông Sơn', null, '-519-Huyện Nông Sơn-Nông Sơn-', 'nongson', null),
        (419, 48, '49', '517', 'Huyện Núi Thành', 'Huyện Núi Thành', 'Núi Thành', null, '-517-Huyện Núi Thành-Núi Thành-', 'nuithanh', null),
        (420, 13, '92', '917', 'Quận Ô Môn', 'Quận Ô Môn', 'Quận Ô Môn', null, '-917-Quận Ô Môn-Quận Ô Môn-', 'quanomon', null),
        (421, 4, '06', '060', 'Huyện Pác Nặm', 'Huyện Pác Nặm', 'Pác Nặm', null, '-060-Huyện Pác Nặm-Pác Nặm-', 'pacnam', null),
        (422, 44, '58', '582', 'Thành phố Phan Rang-Tháp Chàm', 'Thành phố Phan Rang-Tháp Chàm', 'Phan Rang-Tháp Chàm', null, '-582-Thành phố Phan Rang-Tháp Chàm-Phan Rang-Tháp Chàm-', 'phanrangthapcham', null),
        (423, 10, '60', '593', 'Thành phố Phan Thiết', 'Thành phố Phan Thiết', 'Phan Thiết', null, '-593-Thành phố Phan Thiết-Phan Thiết-', 'phanthiet', null),
        (424, 58, '46', '476', 'Huyện Phong Điền', 'Huyện Phong Điền', 'Phong Điền', null, '-476-Huyện Phong Điền-Phong Điền-', 'phongdien', null),
        (425, 13, '92', '926', 'Huyện Phong Điền', 'Huyện Phong Điền', 'Phong Điền', null, '-926-Huyện Phong Điền-Phong Điền-', 'phongdien', null),
        (426, 36, '12', '109', 'Huyện Phong Thổ', 'Huyện Phong Thổ', 'Phong Thổ', null, '-109-Huyện Phong Thổ-Phong Thổ-', 'phongtho', null),
        (427, 56, '19', '172', 'Huyện Phổ Yên', 'Huyện Phổ Yên', 'Phổ Yên', null, '-172-Huyện Phổ Yên-Phổ Yên-', 'phoyen', null),
        (428, 56, '19', '173', 'Huyện Phú Bình', 'Huyện Phú Bình', 'Phú Bình', null, '-173-Huyện Phú Bình-Phú Bình-', 'phubinh', null),
        (429, 8, '74', '722', 'Huyện Phú Giáo', 'Huyện Phú Giáo', 'Phú Giáo', null, '-722-Huyện Phú Giáo-Phú Giáo-', 'phugiao', null),
        (430, 46, '54', '563', 'Huyện Phú Hoà', 'Huyện Phú Hoà', 'Phú Hoà', null, '-563-Huyện Phú Hoà-Phú Hòa-', 'phuhoa', null),
        (431, 58, '46', '482', 'Huyện Phú Lộc', 'Huyện Phú Lộc', 'Phú Lộc', null, '-482-Huyện Phú Lộc-Phú Lộc-', 'phuloc', null),
        (432, 56, '19', '168', 'Huyện Phú Lương', 'Huyện Phú Lương', 'Phú Lương', null, '-168-Huyện Phú Lương-Phú Lương-', 'phuluong', null),
        (433, 30, '79', '768', 'Quận Phú Nhuận', 'Quận Phú Nhuận', 'Quận Phú Nhuận', null, '-768-Quận Phú Nhuận-Quận Phú Nhuận-', 'quanphunhuan', null),
        (434, 48, '49', '518', 'Huyện Phú Ninh', 'Huyện Phú Ninh', 'Phú Ninh', null, '-518-Huyện Phú Ninh-Phú Ninh-', 'phuninh', null),
        (435, 10, '60', '602', 'Huyện Phú Quý', 'Huyện Phú Quý', 'Phú Quý', null, '-602-Huyện Phú Quý-Phú Quý-', 'phuquy', null),
        (436, 34, '91', '911', 'Huyện Phú Quốc', 'Huyện Phú Quốc', 'Phú Quốc', null, '-911-Huyện Phú Quốc-Phú Quốc-', 'phuquoc', null),
        (437, 1, '89', '888', 'Huyện Phú Tân', 'Huyện Phú Tân', 'Phú Tân', null, '-888-Huyện Phú Tân-Phú Tân-', 'phutan', null),
        (438, 12, '96', '972', 'Huyện Phú Tân', 'Huyện Phú Tân', 'Phú Tân', null, '-972-Huyện Phú Tân-Phú Tân-', 'phutan', null),
        (439, 21, '64', '638', 'Huyện Phú Thiện', 'Huyện Phú Thiện', 'Phú Thiện', null, '-638-Huyện Phú Thiện-Phú Thiện-', 'phuthien', null),
        (440, 45, '25', '228', 'Thị xã Phú Thọ', 'Thị xã Phú Thọ', 'Phú Thọ', null, '-228-Thị xã Phú Thọ-Phú Thọ-', 'phutho', null),
        (441, 58, '46', '478', 'Huyện Phú Vang', 'Huyện Phú Vang', 'Phú Vang', null, '-478-Huyện Phú Vang-Phú Vang-', 'phuvang', null),
        (442, 24, '01', '280', 'Huyện Phú Xuyên', 'Huyện Phú Xuyên', 'Phú Xuyên', null, '-280-Huyện Phú Xuyên-Phú Xuyên-', 'phuxuyen', null),
        (443, 11, '52', '548', 'Huyện Phù Cát', 'Huyện Phù Cát', 'Phù Cát', null, '-548-Huyện Phù Cát-Phù Cát-', 'phucat', null),
        (444, 32, '33', '333', 'Huyện Phù Cừ', 'Huyện Phù Cừ', 'Phù Cừ', null, '-333-Huyện Phù Cừ-Phù Cừ-', 'phucu', null),
        (445, 11, '52', '545', 'Huyện Phù Mỹ', 'Huyện Phù Mỹ', 'Phù Mỹ', null, '-545-Huyện Phù Mỹ-Phù Mỹ-', 'phumy', null),
        (446, 45, '25', '233', 'Huyện Phù Ninh', 'Huyện Phù Ninh', 'Phù Ninh', null, '-233-Huyện Phù Ninh-Phù Ninh-', 'phuninh', null),
        (447, 53, '14', '122', 'Huyện Phù Yên', 'Huyện Phù Yên', 'Phù Yên', null, '-122-Huyện Phù Yên-Phù Yên-', 'phuyen', null),
        (448, 23, '35', '347', 'Thành phố Phủ Lý', 'Thành phố Phủ Lý', 'Phủ Lý', null, '-347-Thành phố Phủ Lý-Phủ Lý-', 'phuly', null),
        (449, 24, '01', '272', 'Huyện Phúc Thọ', 'Huyện Phúc Thọ', 'Phúc Thọ', null, '-272-Huyện Phúc Thọ-Phúc Thọ-', 'phuctho', null),
        (450, 63, '26', '244', 'Thị xã Phúc Yên', 'Thị xã Phúc Yên', 'Phúc Yên', null, '-244-Thị xã Phúc Yên-Phúc Yên-', 'phucyen', null),
        (451, 14, '04', '050', 'Huyện Phục Hoà', 'Huyện Phục Hoà', 'Phục Hoà', null, '-050-Huyện Phục Hoà-Phục Hòa-', 'phuchoa', null),
        (452, 29, '93', '934', 'Huyện Phụng Hiệp', 'Huyện Phụng Hiệp', 'Phụng Hiệp', null, '-934-Huyện Phụng Hiệp-Phụng Hiệp-', 'phunghiep', null),
        (453, 9, '70', '688', 'Thị xã Phước Long', 'Thị xã Phước Long', 'Phước Long', null, '-688-Thị xã Phước Long-Phước Long-', 'phuoclong', null),
        (454, 5, '95', '957', 'Huyện Phước Long', 'Huyện Phước Long', 'Phước Long', null, '-957-Huyện Phước Long-Phước Long-', 'phuoclong', null),
        (455, 48, '49', '511', 'Huyện Phước Sơn', 'Huyện Phước Sơn', 'Phước Sơn', null, '-511-Huyện Phước Sơn-Phước Sơn-', 'phuocson', null),
        (456, 21, '64', '622', 'Thành phố Pleiku', 'Thành phố Pleiku', 'Pleiku', null, '-622-Thành phố Pleiku-Pleiku-', 'pleiku', null),
        (457, 57, '38', '385', 'Huyện Quan Hóa', 'Huyện Quan Hóa', 'Quan Hóa', null, '-385-Huyện Quan Hóa-Quan Hóa-', 'quanhoa', null),
        (458, 57, '38', '387', 'Huyện Quan Sơn', 'Huyện Quan Sơn', 'Quan Sơn', null, '-387-Huyện Quan Sơn-Quan Sơn-', 'quanson', null),
        (459, 22, '02', '029', 'Huyện Quản Bạ', 'Huyện Quản Bạ', 'Quản Bạ', null, '-029-Huyện Quản Bạ-Quản Bạ-', 'quanba', null),
        (460, 22, '02', '035', 'Huyện Quang Bình', 'Huyện Quang Bình', 'Quang Bình', null, '-035-Huyện Quang Bình-Quang Bình-', 'quangbinh', null),
        (461, 58, '46', '477', 'Huyện Quảng Điền', 'Huyện Quảng Điền', 'Quảng Điền', null, '-477-Huyện Quảng Điền-Quảng Điền-', 'quangdien', null),
        (462, 49, '51', '522', 'Thành phố Quảng Ngãi', 'Thành phố Quảng Ngãi', 'Quảng Ngãi', null, '-522-Thành phố Quảng Ngãi-Quảng Ngãi-', 'quangngai', null),
        (463, 47, '44', '456', 'Huyện Quảng Ninh', 'Huyện Quảng Ninh', 'Quảng Ninh', null, '-456-Huyện Quảng Ninh-Quảng Ninh-', 'quangninh', null),
        (464, 47, '44', '454', 'Huyện Quảng Trạch', 'Huyện Quảng Trạch', 'Quảng Trạch', null, '-454-Huyện Quảng Trạch-Quảng Trạch-', 'quangtrach', null),
        (465, 51, '45', '462', 'Thị xã Quảng Trị', 'Thị xã Quảng Trị', 'Quảng Trị', null, '-462-Thị xã Quảng Trị-Quảng Trị-', 'quangtri', null),
        (466, 50, '22', '206', 'Thị xã Quảng Yên', 'Thị xã Quảng Yên', 'Quảng Yên', null, '-206-Thị xã Quảng Yên-Quảng Yên-', 'quangyen', null),
        (467, 14, '04', '049', 'Huyện Quảng Uyên', 'Huyện Quảng Uyên', 'Quảng Uyên', null, '-049-Huyện Quảng Uyên-Quảng Uyên-', 'quanguyen', null),
        (468, 57, '38', '406', 'Huyện Quảng Xương', 'Huyện Quảng Xương', 'Quảng Xương', null, '-406-Huyện Quảng Xương-Quảng Xương-', 'quangxuong', null),
        (469, 30, '79', '760', 'Quận 1', 'Quận 1', 'Quận 1', null, '-760-Quận 1-Quận 1-', 'quan1', null),
        (470, 30, '79', '769', 'Quận 2', 'Quận 2', 'Quận 2', null, '-769-Quận 2-Quận 2-', 'quan2', null),
        (471, 30, '79', '770', 'Quận 3', 'Quận 3', 'Quận 3', null, '-770-Quận 3-Quận 3-', 'quan3', null),
        (472, 30, '79', '773', 'Quận 4', 'Quận 4', 'Quận 4', null, '-773-Quận 4-Quận 4-', 'quan4', null),
        (473, 30, '79', '774', 'Quận 5', 'Quận 5', 'Quận 5', null, '-774-Quận 5-Quận 5-', 'quan5', null),
        (474, 30, '79', '775', 'Quận 6', 'Quận 6', 'Quận 6', null, '-775-Quận 6-Quận 6-', 'quan6', null),
        (475, 30, '79', '778', 'Quận 7', 'Quận 7', 'Quận 7', null, '-778-Quận 7-Quận 7-', 'quan7', null),
        (476, 30, '79', '776', 'Quận 8', 'Quận 8', 'Quận 8', null, '-776-Quận 8-Quận 8-', 'quan8', null),
        (477, 30, '79', '763', 'Quận 9', 'Quận 9', 'Quận 9', null, '-763-Quận 9-Quận 9-', 'quan9', null),
        (478, 30, '79', '771', 'Quận 10', 'Quận 10', 'Quận 10', null, '-771-Quận 10-Quận 10-', 'quan10', null),
        (479, 30, '79', '772', 'Quận 11', 'Quận 11', 'Quận 11', null, '-772-Quận 11-Quận 11-', 'quan11', null),
        (480, 30, '79', '761', 'Quận 12', 'Quận 12', 'Quận 12', null, '-761-Quận 12-Quận 12-', 'quan12', null),
        (481, 42, '40', '415', 'Huyện Quế Phong', 'Huyện Quế Phong', 'Quế Phong', null, '-415-Huyện Quế Phong-Quế Phong-', 'quephong', null),
        (482, 48, '49', '509', 'Huyện Quế Sơn', 'Huyện Quế Sơn', 'Quế Sơn', null, '-509-Huyện Quế Sơn-Quế Sơn-', 'queson', null),
        (483, 6, '27', '259', 'Huyện Quế Võ', 'Huyện Quế Võ', 'Quế Võ', null, '-259-Huyện Quế Võ-Quế Võ-', 'quevo', null),
        (484, 11, '52', '540', 'Thành phố Quy Nhơn', 'Thành phố Quy Nhơn', 'Quy Nhơn', null, '-540-Thành phố Qui Nhơn-Qui Nhơn-', 'quynhon', null),
        (485, 24, '01', '275', 'Huyện Quốc Oai', 'Huyện Quốc Oai', 'Quốc Oai', null, '-275-Huyện Quốc Oai-Quốc Oai-', 'quocoai', null),
        (486, 42, '40', '416', 'Huyện Quỳ Châu', 'Huyện Quỳ Châu', 'Quỳ Châu', null, '-416-Huyện Quỳ Châu-Quỳ Châu-', 'quychau', null),
        (487, 42, '40', '420', 'Huyện Quỳ Hợp', 'Huyện Quỳ Hợp', 'Quỳ Hợp', null, '-420-Huyện Quỳ Hợp-Quỳ Hợp-', 'quyhop', null),
        (488, 42, '40', '421', 'Huyện Quỳnh Lưu', 'Huyện Quỳnh Lưu', 'Quỳnh Lưu', null, '-421-Huyện Quỳnh Lưu-Quỳnh Lưu-', 'quynhluu', null),
        (489, 53, '14', '118', 'Huyện Quỳnh Nhai', 'Huyện Quỳnh Nhai', 'Quỳnh Nhai', null, '-118-Huyện Quỳnh Nhai-Quỳnh Nhai-', 'quynhnhai', null),
        (490, 55, '34', '338', 'Huyện Quỳnh Phụ', 'Huyện Quỳnh Phụ', 'Quỳnh Phụ', null, '-338-Huyện Quỳnh Phụ-Quỳnh Phụ-', 'quynhphu', null),
        (491, 34, '91', '899', 'Thành phố Rạch Giá', 'Thành phố Rạch Giá', 'Rạch Giá', null, '-899-Thành phố Rạch Giá-Rạch Giá-', 'rachgia', null),
        (492, 20, '87', '867', 'Thành phố Sa Đéc', 'Thành phố Sa Đéc', 'Sa Đéc', null, '-867-Thành phố Sa Đéc-Sa Đéc-', 'sadec', null),
        (493, 39, '10', '088', 'Huyện Sa Pa', 'Huyện Sa Pa', 'Sa Pa', null, '-088-Huyện Sa Pa-Sa Pa-', 'sapa', null),
        (494, 35, '62', '616', 'Huyện Sa Thầy', 'Huyện Sa Thầy', 'Sa Thầy', null, '-616-Huyện Sa Thầy-Sa Thầy-', 'sathay', null),
        (495, 57, '38', '382', 'Thị xã Sầm Sơn', 'Thành phố Sầm Sơn', 'Sầm Sơn', null, '-382-Thị xã Sầm Sơn-Sầm Sơn-', 'samson', null),
        (496, 39, '10', '084', 'Huyện Si Ma Cai', 'Huyện Si Ma Cai', 'Si Ma Cai', null, '-084-Huyện Si Ma Cai-Si Ma Cai-', 'simacai', null),
        (497, 36, '12', '108', 'Huyện Sìn Hồ', 'Huyện Sìn Hồ', 'Sìn Hồ', null, '-108-Huyện Sìn Hồ-Sìn Hồ-', 'sinho', null),
        (498, 24, '01', '016', 'Huyện Sóc Sơn', 'Huyện Sóc Sơn', 'Sóc Sơn', null, '-016-Huyện Sóc Sơn-Sóc Sơn-', 'socson', null),
        (499, 52, '94', '941', 'Thành phố Sóc Trăng', 'Thành phố Sóc Trăng', 'Sóc Trăng', null, '-941-Thành phố Sóc Trăng-Sóc Trăng-', 'soctrang', null),
        (500, 46, '54', '557', 'Thị xã Sông Cầu', 'Thị xã Sông Cầu', 'Sông Cầu', null, '-557-Thị xã Sông Cầu-Sông Cầu-', 'songcau', null),
        (501, 56, '19', '165', 'Thị xã Sông Công', 'Thị xã Sông Công', 'Sông Công', null, '-165-Thị xã Sông Công-Sông Công-', 'songcong', null),
        (502, 46, '54', '561', 'Huyện Sông Hinh', 'Huyện Sông Hinh', 'Sông Hinh', null, '-561-Huyện Sông Hinh-Sông Hinh-', 'songhinh', null),
        (503, 63, '26', '253', 'Huyện Sông Lô', 'Huyện Sông Lô', 'Sông Lô', null, '-253-Huyện Sông Lô-Sông Lô-', 'songlo', null),
        (504, 53, '14', '126', 'Huyện Sông Mã', 'Huyện Sông Mã', 'Sông Mã', null, '-126-Huyện Sông Mã-Sông Mã-', 'songma', null),
        (505, 53, '14', '127', 'Huyện Sốp Cộp', 'Huyện Sốp Cộp', 'Sốp Cộp', null, '-127-Huyện Sốp Cộp-Sốp Cộp-', 'sopcop', null),
        (506, 3, '24', '220', 'Huyện Sơn Động', 'Huyện Sơn Động', 'Sơn Động', null, '-220-Huyện Sơn Động-Sơn Động-', 'sondong', null),
        (507, 61, '08', '076', 'Huyện Sơn Dương', 'Huyện Sơn Dương', 'Sơn Dương', null, '-076-Huyện Sơn Dương-Sơn Dương-', 'sonduong', null),
        (508, 49, '51', '529', 'Huyện Sơn Hà', 'Huyện Sơn Hà', 'Sơn Hà', null, '-529-Huyện Sơn Hà-Sơn Hà-', 'sonha', null),
        (509, 46, '54', '560', 'Huyện Sơn Hòa', 'Huyện Sơn Hòa', 'Sơn Hòa', null, '-560-Huyện Sơn Hòa-Sơn Hòa-', 'sonhoa', null),
        (510, 53, '14', '116', 'Thành phố Sơn La', 'Thành phố Sơn La', 'Sơn La', null, '-116-Thành phố Sơn La-Sơn La-', 'sonla', null),
        (511, 24, '01', '269', 'Thị xã Sơn Tây', 'Thị xã Sơn Tây', 'Sơn Tây', null, '-269-Thị xã Sơn Tây-Sơn Tây-', 'sontay', null),
        (512, 49, '51', '530', 'Huyện Sơn Tây', 'Huyện Sơn Tây', 'Sơn Tây', null, '-530-Huyện Sơn Tây-Sơn Tây-', 'sontay', null),
        (513, 49, '51', '527', 'Huyện Sơn Tịnh', 'Huyện Sơn Tịnh', 'Sơn Tịnh', null, '-527-Huyện Sơn Tịnh-Sơn Tịnh-', 'sontinh', null),
        (514, 15, '48', '493', 'Quận Sơn Trà', 'Quận Sơn Trà', 'Sơn Trà', null, '-493-Quận Sơn Trà-Quận Sơn Trà-', 'sontra', null),
        (515, 62, '86', '860', 'Huyện Tam Bình', 'Huyện Tam Bình', 'Tam Bình', null, '-860-Huyện Tam Bình-Tam Bình-', 'tambinh', null),
        (516, 63, '26', '247', 'Huyện Tam Dương', 'Huyện Tam Dương', 'Tam Dương', null, '-247-Huyện Tam Dương-Tam Dương-', 'tamduong', null),
        (517, 63, '26', '248', 'Huyện Tam Đảo', 'Huyện Tam Đảo', 'Tam Đảo', null, '-248-Huyện Tam Đảo-Tam Đảo-', 'tamdao', null),
        (518, 43, '37', '370', 'Thành phố Tam Điệp', 'Thành phố Tam Điệp', 'Tam Điệp', null, '-370-Thành phố Tam Điệp-Tam Điệp-', 'tamdiep', null),
        (519, 36, '12', '106', 'Huyện Tam Đường', 'Huyện Tam Đường', 'Tam Đường', null, '-106-Huyện Tam Đường-Tam Đường-', 'tamduong', null),
        (520, 48, '49', '502', 'Thành phố Tam Kỳ', 'Thành phố Tam Kỳ', 'Tam Kỳ', null, '-502-Thành phố Tam Kỳ-Tam Kỳ-', 'tamky', null),
        (521, 20, '87', '871', 'Huyện Tam Nông', 'Huyện Tam Nông', 'Tam Nông', null, '-871-Huyện Tam Nông-Tam Nông-', 'tamnong', null),
        (522, 45, '25', '236', 'Huyện Tam Nông', 'Huyện Tam Nông', 'Tam Nông', null, '-236-Huyện Tam Nông-Tam Nông-', 'tamnong', null),
        (523, 10, '60', '599', 'Huyện Tánh Linh', 'Huyện Tánh Linh', 'Tánh Linh', null, '-599-Huyện Tánh Linh-Tánh Linh-', 'tanhlinh', null),
        (524, 40, '80', '794', 'Thành phố Tân An', 'Thành phố Tân An', 'Tân An', null, '-794-Thành phố Tân An-Tân An-', 'tanan', null),
        (525, 54, '72', '705', 'Huyện Tân Biên', 'Huyện Tân Biên', 'Tân Biên', null, '-705-Huyện Tân Biên-Tân Biên-', 'tanbien', null),
        (526, 30, '79', '766', 'Quận Tân Bình', 'Quận Tân Bình', 'Quận Tân Bình', null, '-766-Quận Tân Bình-Quận Tân Bình-', 'quantanbinh', null),
        (527, 1, '89', '887', 'Thị xã Tân Châu', 'Thị xã Tân Châu', 'Tân Châu', null, '-887-Thị xã Tân Châu-Tân Châu-', 'tanchau', null),
        (528, 54, '72', '706', 'Huyện Tân Châu', 'Huyện Tân Châu', 'Tân Châu', null, '-706-Huyện Tân Châu-Tân Châu-', 'tanchau', null),
        (529, 34, '91', '904', 'Huyện Tân Hiệp', 'Huyện Tân Hiệp', 'Tân Hiệp', null, '-904-Huyện Tân Hiệp-Tân Hiệp-', 'tanhiep', null),
        (530, 20, '87', '869', 'Huyện Tân Hồng', 'Huyện Tân Hồng', 'Tân Hồng', null, '-869-Huyện Tân Hồng-Tân Hồng-', 'tanhong', null),
        (531, 40, '80', '796', 'Huyện Tân Hưng', 'Huyện Tân Hưng', 'Tân Hưng', null, '-796-Huyện Tân Hưng-Tân Hưng-', 'tanhung', null),
        (532, 42, '40', '423', 'Huyện Tân Kỳ', 'Huyện Tân Kỳ', 'Tân Kỳ', null, '-423-Huyện Tân Kỳ-Tân Kỳ-', 'tanky', null),
        (533, 31, '17', '155', 'Huyện Tân Lạc', 'Huyện Tân Lạc', 'Tân Lạc', null, '-155-Huyện Tân Lạc-Tân Lạc-', 'tanlac', null),
        (534, 19, '75', '734', 'Huyện Tân Phú', 'Huyện Tân Phú', 'Tân Phú', null, '-734-Huyện Tân Phú-Tân Phú-', 'tanphu', null),
        (535, 30, '79', '767', 'Quận Tân Phú', 'Quận Tân Phú', 'Quận Tân Phú', null, '-767-Quận Tân Phú-Quận Tân Phú-', 'quantanphu', null),
        (536, 59, '82', '825', 'Huyện Tân Phú Đông', 'Huyện Tân Phú Đông', 'Tân Phú Đông', null, '-825-Huyện Tân Phú Đông-Tân Phú Đông-', 'tanphudong', null),
        (537, 59, '82', '818', 'Huyện Tân Phước', 'Huyện Tân Phước', 'Tân Phước', null, '-818-Huyện Tân Phước-Tân Phước-', 'tanphuoc', null),
        (538, 45, '25', '240', 'Huyện Tân Sơn', 'Huyện Tân Sơn', 'Tân Sơn', null, '-240-Huyện Tân Sơn-Tân Sơn-', 'tanson', null),
        (539, 2, '77', '754', 'Thị Xã Phú Mỹ', 'Thị Xã Phú Mỹ', 'Phú Mỹ', null, '-754-Huyện Tân Thành-Tân Thành-', 'phumy', null),
        (540, 40, '80', '799', 'Huyện Tân Thạnh', 'Huyện Tân Thạnh', 'Tân Thạnh', null, '-799-Huyện Tân Thạnh-Tân Thạnh-', 'tanthanh', null),
        (541, 40, '80', '805', 'Huyện Tân Trụ', 'Huyện Tân Trụ', 'Tân Trụ', null, '-805-Huyện Tân Trụ-Tân Trụ-', 'tantru', null),
        (542, 8, '74', '723', 'Thị xã Tân Uyên', 'Thị xã Tân Uyên', 'Tân Uyên', null, '-723-Thị xã Tân Uyên-Tân Uyên-', 'tanuyen', null),
        (543, 36, '12', '111', 'Huyện Tân Uyên', 'Huyện Tân Uyên', 'Tân Uyên', null, '-111-Huyện Tân Uyên-Tân Uyên-', 'tanuyen', null),
        (544, 3, '24', '216', 'Huyện Tân Yên', 'Huyện Tân Yên', 'Tân Yên', null, '-216-Huyện Tân Yên-Tân Yên-', 'tanyen', null),
        (545, 48, '49', '504', 'Huyện Tây Giang', 'Huyện Tây Giang', 'Tây Giang', null, '-504-Huyện Tây Giang-Tây Giang-', 'taygiang', null),
        (546, 46, '54', '562', 'Huyện Tây Hoà', 'Huyện Tây Hoà', 'Tây Hoà', null, '-562-Huyện Tây Hoà-Tây Hòa-', 'tayhoa', null),
        (547, 24, '01', '003', 'Quận Tây Hồ', 'Quận Tây Hồ', 'Quận Tây Hồ', null, '-003-Quận Tây Hồ-Quận Tây Hồ-', 'quantayho', null),
        (548, 54, '72', '703', 'Thành phố Tây Ninh', 'Thành phố Tây Ninh', 'Tây Ninh', null, '-703-Thành phố Tây Ninh-Tây Ninh-', 'tayninh', null),
        (549, 11, '52', '547', 'Huyện Tây Sơn', 'Huyện Tây Sơn', 'Tây Sơn', null, '-547-Huyện Tây Sơn-Tây Sơn-', 'tayson', null),
        (550, 49, '51', '526', 'Huyện Tây Trà', 'Huyện Tây Trà', 'Tây Trà', null, '-526-Huyện Tây Trà-Tây Trà-', 'taytra', null),
        (551, 14, '04', '053', 'Huyện Thạch An', 'Huyện Thạch An', 'Thạch An', null, '-053-Huyện Thạch An-Thạch An-', 'thachan', null),
        (552, 26, '42', '445', 'Huyện Thạch Hà', 'Huyện Thạch Hà', 'Thạch Hà', null, '-445-Huyện Thạch Hà-Thạch Hà-', 'thachha', null),
        (553, 57, '38', '391', 'Huyện Thạch Thành', 'Huyện Thạch Thành', 'Thạch Thành', null, '-391-Huyện Thạch Thành-Thạch Thành-', 'thachthanh', null),
        (554, 24, '01', '276', 'Huyện Thạch Thất', 'Huyện Thạch Thất', 'Thạch Thất', null, '-276-Huyện Thạch Thất-Thạch Thất-', 'thachthat', null),
        (555, 55, '34', '336', 'Thành phố Thái Bình', 'Thành phố Thái Bình', 'Thái Bình', null, '-336-Thành phố Thái Bình-Thái Bình-', 'thaibinh', null),
        (556, 42, '40', '414', 'Thị xã Thái Hoà', 'Thị xã Thái Hoà', 'Thái Hoà', null, '-414-Thị xã Thái Hoà-Thái Hòa-', 'thaihoa', null),
        (557, 56, '19', '164', 'Thành phố Thái Nguyên', 'Thành phố Thái Nguyên', 'Thái Nguyên', null, '-164-Thành phố Thái Nguyên-Thái Nguyên-', 'thainguyen', null),
        (558, 55, '34', '341', 'Huyện Thái Thụy', 'Huyện Thái Thụy', 'Thái Thụy', null, '-341-Huyện Thái Thụy-Thái Thụy-', 'thaithuy', null),
        (559, 36, '12', '110', 'Huyện Than Uyên', 'Huyện Than Uyên', 'Than Uyên', null, '-110-Huyện Than Uyên-Than Uyên-', 'thanuyen', null),
        (560, 45, '25', '232', 'Huyện Thanh Ba', 'Huyện Thanh Ba', 'Thanh Ba', null, '-232-Huyện Thanh Ba-Thanh Ba-', 'thanhba', null),
        (561, 20, '87', '874', 'Huyện Thanh Bình', 'Huyện Thanh Bình', 'Thanh Bình', null, '-874-Huyện Thanh Bình-Thanh Bình-', 'thanhbinh', null),
        (562, 42, '40', '428', 'Huyện Thanh Chương', 'Huyện Thanh Chương', 'Thanh Chương', null, '-428-Huyện Thanh Chương-Thanh Chương-', 'thanhchuong', null),
        (563, 27, '30', '294', 'Huyện Thanh Hà', 'Huyện Thanh Hà', 'Thanh Hà', null, '-294-Huyện Thanh Hà-Thanh Hà-', 'thanhha', null),
        (564, 57, '38', '380', 'Thành phố Thanh Hóa', 'Thành phố Thanh Hóa', 'TP Thanh Hóa', null, '-380-Thành phố Thanh Hóa-Thanh Hóa-', 'tpthanhhoa', null),
        (565, 15, '48', '491', 'Quận Thanh Khê', 'Quận Thanh Khê', 'Thanh Khê', null, '-491-Quận Thanh Khê-Quận Thanh Khê-', 'thanhkhe', null),
        (566, 23, '35', '351', 'Huyện Thanh Liêm', 'Huyện Thanh Liêm', 'Thanh Liêm', null, '-351-Huyện Thanh Liêm-Thanh Liêm-', 'thanhliem', null),
        (567, 27, '30', '300', 'Huyện Thanh Miện', 'Huyện Thanh Miện', 'Thanh Miện', null, '-300-Huyện Thanh Miện-Thanh Miện-', 'thanhmien', null),
        (568, 24, '01', '278', 'Huyện Thanh Oai', 'Huyện Thanh Oai', 'Thanh Oai', null, '-278-Huyện Thanh Oai-Thanh Oai-', 'thanhoai', null),
        (569, 45, '25', '238', 'Huyện Thanh Sơn', 'Huyện Thanh Sơn', 'Thanh Sơn', null, '-238-Huyện Thanh Sơn-Thanh Sơn-', 'thanhson', null),
        (570, 45, '25', '239', 'Huyện Thanh Thuỷ', 'Huyện Thanh Thuỷ', 'Thanh Thuỷ', null, '-239-Huyện Thanh Thuỷ-Thanh Thủy-', 'thanhthuy', null),
        (571, 24, '01', '020', 'Huyện Thanh Trì', 'Huyện Thanh Trì', 'Thanh Trì', null, '-020-Huyện Thanh Trì-Thanh Trì-', 'thanhtri', null),
        (572, 24, '01', '009', 'Quận Thanh Xuân', 'Quận Thanh Xuân', 'Quận Thanh Xuân', null, '-009-Quận Thanh Xuân-Quận Thanh Xuân-', 'quanthanhxuan', null),
        (573, 40, '80', '800', 'Huyện Thạnh Hóa', 'Huyện Thạnh Hóa', 'Thạnh Hóa', null, '-800-Huyện Thạnh Hóa-Thạnh Hóa-', 'thanhhoa', null),
        (574, 7, '83', '837', 'Huyện Thạnh Phú', 'Huyện Thạnh Phú', 'Thạnh Phú', null, '-837-Huyện Thạnh Phú-Thạnh Phú-', 'thanhphu', null),
        (575, 52, '94', '949', 'Huyện Thạnh Trị', 'Huyện Thạnh Trị', 'Thạnh Trị', null, '-949-Huyện Thạnh Trị-Thạnh Trị-', 'thanhtri', null),
        (576, 20, '87', '872', 'Huyện Tháp Mười', 'Huyện Tháp Mười', 'Tháp Mười', null, '-872-Huyện Tháp Mười-Tháp Mười-', 'thapmuoi', null),
        (577, 48, '49', '513', 'Huyện Thăng Bình', 'Huyện Thăng Bình', 'Thăng Bình', null, '-513-Huyện Thăng Bình-Thăng Bình-', 'thangbinh', null),
        (578, 57, '38', '398', 'Huyện Thiệu Hóa', 'Huyện Thiệu Hóa', 'Thiệu Hóa', null, '-398-Huyện Thiệu Hóa-Thiệu Hóa-', 'thieuhoa', null),
        (579, 57, '38', '395', 'Huyện Thọ Xuân', 'Huyện Thọ Xuân', 'Thọ Xuân', null, '-395-Huyện Thọ Xuân-Thọ Xuân-', 'thoxuan', null),
        (580, 1, '89', '894', 'Huyện Thoại Sơn', 'Huyện Thoại Sơn', 'Thoại Sơn', null, '-894-Huyện Thoại Sơn-Thoại Sơn-', 'thoaison', null),
        (581, 14, '04', '044', 'Huyện Thông Nông', 'Huyện Thông Nông', 'Thông Nông', null, '-044-Huyện Thông Nông-Thông Nông-', 'thongnong', null),
        (582, 19, '75', '738', 'Huyện Thống Nhất', 'Huyện Thống Nhất', 'Thống Nhất', null, '-738-Huyện Thống Nhất-Thống Nhất-', 'thongnhat', null),
        (583, 13, '92', '923', 'Quận Thốt Nốt', 'Quận Thốt Nốt', 'Quận Thốt Nốt', null, '-923-Quận Thốt Nốt-Quận Thốt Nốt-', 'quanthotnot', null),
        (584, 12, '96', '967', 'Huyện Thới Bình', 'Huyện Thới Bình', 'Thới Bình', null, '-967-Huyện Thới Bình-Thới Bình-', 'thoibinh', null),
        (585, 13, '92', '927', 'Huyện Thới Lai', 'Huyện Thới Lai', 'Thới Lai', null, '-927-Huyện Thới Lai-Thới Lai-', 'thoilai', null),
        (586, 8, '74', '718', 'Thành phố Thủ Dầu Một', 'Thành phố Thủ Dầu Một', 'Thủ Dầu Một', null, '-718-Thành phố Thủ Dầu Một-Thủ Dầu Một-', 'thudaumot', null),
        (587, 30, '79', '762', 'Quận Thủ Đức', 'Quận Thủ Đức', 'Quận Thủ Đức', null, '-762-Quận Thủ Đức-Quận Thủ Đức-', 'quanthuduc', null),
        (588, 40, '80', '804', 'Huyện Thủ Thừa', 'Huyện Thủ Thừa', 'Thủ Thừa', null, '-804-Huyện Thủ Thừa-Thủ Thừa-', 'thuthua', null),
        (589, 8, '74', '725', 'Thị xã Thuận An', 'Thị xã Thuận An', 'Thuận An', null, '-725-Thị xã Thuận An-Thuận An-', 'thuanan', null),
        (590, 44, '58', '588', 'Huyện Thuận Bắc', 'Huyện Thuận Bắc', 'Thuận Bắc', null, '-588-Huyện Thuận Bắc-Thuận Bắc-', 'thuanbac', null),
        (591, 53, '14', '119', 'Huyện Thuận Châu', 'Huyện Thuận Châu', 'Thuận Châu', null, '-119-Huyện Thuận Châu-Thuận Châu-', 'thuanchau', null),
        (592, 44, '58', '589', 'Huyện Thuận Nam', 'Huyện Thuận Nam', 'Thuận Nam', null, '-589-Huyện Thuận Nam-Thuận Nam-', 'thuannam', null),
        (593, 6, '27', '262', 'Huyện Thuận Thành', 'Huyện Thuận Thành', 'Thuận Thành', null, '-262-Huyện Thuận Thành-Thuận Thành-', 'thuanthanh', null),
        (594, 28, '31', '311', 'Huyện Thuỷ Nguyên', 'Huyện Thuỷ Nguyên', 'Thuỷ Nguyên', null, '-311-Huyện Thuỷ Nguyên-Thuỷ Nguyên-', 'thuynguyen', null),
        (595, 24, '01', '279', 'Huyện Thường Tín', 'Huyện Thường Tín', 'Thường Tín', null, '-279-Huyện Thường Tín-Thường Tín-', 'thuongtin', null),
        (596, 57, '38', '396', 'Huyện Thường Xuân', 'Huyện Thường Xuân', 'Thường Xuân', null, '-396-Huyện Thường Xuân-Thường Xuân-', 'thuongxuan', null),
        (597, 6, '27', '260', 'Huyện Tiên Du', 'Huyện Tiên Du', 'Tiên Du', null, '-260-Huyện Tiên Du-Tiên Du-', 'tiendu', null),
        (598, 55, '34', '342', 'Huyện Tiền Hải', 'Huyện Tiền Hải', 'Tiền Hải', null, '-342-Huyện Tiền Hải-Tiền Hải-', 'tienhai', null),
        (599, 28, '31', '315', 'Huyện Tiên Lãng', 'Huyện Tiên Lãng', 'Tiên Lãng', null, '-315-Huyện Tiên Lãng-Tiên Lãng-', 'tienlang', null),
        (600, 32, '33', '332', 'Huyện Tiên Lữ', 'Huyện Tiên Lữ', 'Tiên Lữ', null, '-332-Huyện Tiên Lữ-Tiên Lữ-', 'tienlu', null),
        (601, 48, '49', '514', 'Huyện Tiên Phước', 'Huyện Tiên Phước', 'Tiên Phước', null, '-514-Huyện Tiên Phước-Tiên Phước-', 'tienphuoc', null),
        (602, 50, '22', '199', 'Huyện Tiên Yên', 'Huyện Tiên Yên', 'Tiên Yên', null, '-199-Huyện Tiên Yên-Tiên Yên-', 'tienyen', null),
        (603, 60, '84', '846', 'Huyện Tiểu Cần', 'Huyện Tiểu Cần', 'Tiểu Cần', null, '-846-Huyện Tiểu Cần-Tiểu Cần-', 'tieucan', null),
        (604, 57, '38', '407', 'Huyện Tĩnh Gia', 'Huyện Tĩnh Gia', 'Tĩnh Gia', null, '-407-Huyện Tĩnh Gia-Tĩnh Gia-', 'tinhgia', null),
        (605, 1, '89', '890', 'Huyện Tịnh Biên', 'Huyện Tịnh Biên', 'Tịnh Biên', null, '-890-Huyện Tịnh Biên-Tịnh Biên-', 'tinhbien', null),
        (606, 49, '51', '525', 'Huyện Trà Bồng', 'Huyện Trà Bồng', 'Trà Bồng', null, '-525-Huyện Trà Bồng-Trà Bồng-', 'trabong', null),
        (607, 60, '84', '849', 'Huyện Trà Cú', 'Huyện Trà Cú', 'Trà Cú', null, '-849-Huyện Trà Cú-Trà Cú-', 'tracu', null),
        (608, 14, '04', '046', 'Huyện Trà Lĩnh', 'Huyện Trà Lĩnh', 'Trà Lĩnh', null, '-046-Huyện Trà Lĩnh-Trà Lĩnh-', 'tralinh', null),
        (609, 62, '86', '862', 'Huyện Trà Ôn', 'Huyện Trà Ôn', 'Trà Ôn', null, '-862-Huyện Trà Ôn-Trà Ôn-', 'traon', null),
        (610, 60, '84', '842', 'Thành phố Trà Vinh', 'Thành phố Trà Vinh', 'Trà Vinh', null, '-842-Thành phố Trà Vinh-Trà Vinh-', 'travinh', null),
        (611, 64, '15', '139', 'Huyện Trạm Tấu', 'Huyện Trạm Tấu', 'Trạm Tấu', null, '-139-Huyện Trạm Tấu-Trạm Tấu-', 'tramtau', null),
        (612, 38, '20', '180', 'Huyện Tràng Định', 'Huyện Tràng Định', 'Tràng Định', null, '-180-Huyện Tràng Định-Tràng Định-', 'trangdinh', null),
        (613, 54, '72', '712', 'Huyện Trảng Bàng', 'Huyện Trảng Bàng', 'Trảng Bàng', null, '-712-Huyện Trảng Bàng-Trảng Bàng-', 'trangbang', null),
        (614, 19, '75', '737', 'Huyện Trảng Bom', 'Huyện Trảng Bom', 'Trảng Bom', null, '-737-Huyện Trảng Bom-Trảng Bom-', 'trangbom', null),
        (615, 64, '15', '138', 'Huyện Trấn Yên', 'Huyện Trấn Yên', 'Trấn Yên', null, '-138-Huyện Trấn Yên-Trấn Yên-', 'tranyen', null),
        (616, 52, '94', '951', 'Huyện Trần Đề', 'Huyện Trần Đề', 'Trần Đề', null, '-951-Huyện Trần Đề-Trần Đề-', 'trande', null),
        (617, 12, '96', '968', 'Huyện Trần Văn Thời', 'Huyện Trần Văn Thời', 'Trần Văn Thời', null, '-968-Huyện Trần Văn Thời-Trần Văn Thời-', 'tranvanthoi', null),
        (618, 1, '89', '891', 'Huyện Tri Tôn', 'Huyện Tri Tôn', 'Tri Tôn', null, '-891-Huyện Tri Tôn-Tri Tôn-', 'triton', null),
        (619, 51, '45', '469', 'Huyện Triệu Phong', 'Huyện Triệu Phong', 'Triệu Phong', null, '-469-Huyện Triệu Phong-Triệu Phong-', 'trieuphong', null),
        (620, 57, '38', '397', 'Huyện Triệu Sơn', 'Huyện Triệu Sơn', 'Triệu Sơn', null, '-397-Huyện Triệu Sơn-Triệu Sơn-', 'trieuson', null),
        (621, 14, '04', '047', 'Huyện Trùng Khánh', 'Huyện Trùng Khánh', 'Trùng Khánh', null, '-047-Huyện Trùng Khánh-Trùng Khánh-', 'trungkhanh', null),
        (622, 41, '36', '363', 'Huyện Trực Ninh', 'Huyện Trực Ninh', 'Trực Ninh', null, '-363-Huyện Trực Ninh-Trực Ninh-', 'trucninh', null),
        (623, 33, '56', '576', 'Huyện Trường Sa', 'Huyện Trường Sa', 'Trường Sa', null, '-576-Huyện Trường Sa-Trường Sa-', 'truongsa', null),
        (624, 18, '11', '098', 'Huyện Tủa Chùa', 'Huyện Tủa Chùa', 'Tủa Chùa', null, '-098-Huyện Tủa Chùa-Tủa Chùa-', 'tuachua', null),
        (625, 18, '11', '099', 'Huyện Tuần Giáo', 'Huyện Tuần Giáo', 'Tuần Giáo', null, '-099-Huyện Tuần Giáo-Tuần Giáo-', 'tuangiao', null),
        (626, 35, '62', '617', 'Huyện Tu Mơ Rông', 'Huyện Tu Mơ Rông', 'Tu Mơ Rông', null, '-617-Huyện Tu Mơ Rông-Tu Mơ Rông-', 'tumorong', null),
        (627, 46, '54', '559', 'Huyện Tuy An', 'Huyện Tuy An', 'Tuy An', null, '-559-Huyện Tuy An-Tuy An-', 'tuyan', null),
        (628, 17, '67', '667', 'Huyện Tuy Đức', 'Huyện Tuy Đức', 'Tuy Đức', null, '-667-Huyện Tuy Đức-Tuy Đức-', 'tuyduc', null),
        (629, 46, '54', '555', 'Thành phố Tuy Hoà', 'Thành phố Tuy Hoà', 'Tuy Hoà', null, '-555-Thành phố Tuy Hoà-Tuy Hòa-', 'tuyhoa', null),
        (630, 10, '60', '595', 'Huyện Tuy Phong', 'Huyện Tuy Phong', 'Tuy Phong', null, '-595-Huyện Tuy Phong-Tuy Phong-', 'tuyphong', null),
        (631, 11, '52', '550', 'Huyện Tuy Phước', 'Huyện Tuy Phước', 'Tuy Phước', null, '-550-Huyện Tuy Phước-Tuy Phước-', 'tuyphuoc', null),
        (632, 47, '44', '453', 'Huyện Tuyên Hóa', 'Huyện Tuyên Hóa', 'Tuyên Hóa', null, '-453-Huyện Tuyên Hóa-Tuyên Hóa-', 'tuyenhoa', null),
        (633, 61, '08', '070', 'Thành phố Tuyên Quang', 'Thành phố Tuyên Quang', 'Tuyên Quang', null, '-070-Thành phố Tuyên Quang-Tuyên Quang-', 'tuyenquang', null),
        (634, 49, '51', '528', 'Huyện Tư Nghĩa', 'Huyện Tư Nghĩa', 'Tư Nghĩa', null, '-528-Huyện Tư Nghĩa-Tư Nghĩa-', 'tunghia', null),
        (635, 27, '30', '298', 'Huyện Tứ Kỳ', 'Huyện Tứ Kỳ', 'Tứ Kỳ', null, '-298-Huyện Tứ Kỳ-Tứ Kỳ-', 'tuky', null),
        (636, 24, '01', '021', 'Quận Bắc Từ Liêm', 'Quận Bắc Từ Liêm', 'Bắc Từ Liêm', null, '-019-Quận Bắc Từ Liêm-Bắc Từ Liêm-', 'bactuliem', null),
        (637, 6, '27', '261', 'Thị xã Từ Sơn', 'Thị xã Từ Sơn', 'Từ Sơn', null, '-261-Thị xã Từ Sơn-Từ Sơn-', 'tuson', null),
        (638, 42, '40', '418', 'Huyện Tương Dương', 'Huyện Tương Dương', 'Tương Dương', null, '-418-Huyện Tương Dương-Tương Dương-', 'tuongduong', null),
        (639, 12, '96', '966', 'Huyện U Minh', 'Huyện U Minh', 'U Minh', null, '-966-Huyện U Minh-U Minh-', 'uminh', null),
        (640, 34, '91', '913', 'Huyện U Minh Thượng', 'Huyện U Minh Thượng', 'U Minh Thượng', null, '-913-Huyện U Minh Thượng-U Minh Thượng-', 'uminhthuong', null),
        (641, 50, '22', '196', 'Thành phố Uông Bí', 'Thành phố Uông Bí', 'Uông Bí', null, '-196-Thành phố Uông Bí-Uông Bí-', 'uongbi', null),
        (642, 24, '01', '281', 'Huyện Ứng Hòa', 'Huyện Ứng Hòa', 'Ứng Hòa', null, '-281-Huyện Ứng Hòa-Ứng Hòa-', 'unghoa', null),
        (643, 33, '56', '571', 'Huyện Vạn Ninh', 'Huyện Vạn Ninh', 'Vạn Ninh', null, '-571-Huyện Vạn Ninh-Vạn Ninh-', 'vanninh', null),
        (644, 39, '10', '089', 'Huyện Văn Bàn', 'Huyện Văn Bàn', 'Văn Bàn', null, '-089-Huyện Văn Bàn-Văn Bàn-', 'vanban', null),
        (645, 64, '15', '140', 'Huyện Văn Chấn', 'Huyện Văn Chấn', 'Văn Chấn', null, '-140-Huyện Văn Chấn-Văn Chấn-', 'vanchan', null),
        (646, 32, '33', '326', 'Huyện Văn Giang', 'Huyện Văn Giang', 'Văn Giang', null, '-326-Huyện Văn Giang-Văn Giang-', 'vangiang', null),
        (647, 38, '20', '182', 'Huyện Văn Lãng', 'Huyện Văn Lãng', 'Văn Lãng', null, '-182-Huyện Văn Lãng-Vãn Lãng-', 'vanlang', null),
        (648, 32, '33', '325', 'Huyện Văn Lâm', 'Huyện Văn Lâm', 'Văn Lâm', null, '-325-Huyện Văn Lâm-Văn Lâm-', 'vanlam', null),
        (649, 38, '20', '184', 'Huyện Văn Quan', 'Huyện Văn Quan', 'Văn Quan', null, '-184-Huyện Văn Quan-Văn Quan-', 'vanquan', null),
        (650, 64, '15', '136', 'Huyện Văn Yên', 'Huyện Văn Yên', 'Văn Yên', null, '-136-Huyện Văn Yên-Văn Yên-', 'vanyen', null),
        (651, 11, '52', '551', 'Huyện Vân Canh', 'Huyện Vân Canh', 'Vân Canh', null, '-551-Huyện Vân Canh-Vân Canh-', 'vancanh', null),
        (652, 50, '22', '203', 'Huyện Vân Đồn', 'Huyện Vân Đồn', 'Vân Đồn', null, '-203-Huyện Vân Đồn-Vân Đồn-', 'vandon', null),
        (653, 29, '93', '930', 'Thành phố Vị Thanh', 'Thành phố Vị Thanh', 'Vị Thanh', null, '-930-Thành phố Vị Thanh-Vị Thanh-', 'vithanh', null),
        (654, 29, '93', '935', 'Huyện Vị Thuỷ', 'Huyện Vị Thuỷ', 'Vị Thuỷ', null, '-935-Huyện Vị Thuỷ-Vị Thủy-', 'vithuy', null),
        (655, 22, '02', '030', 'Huyện Vị Xuyên', 'Huyện Vị Xuyên', 'Vị Xuyên', null, '-030-Huyện Vị Xuyên-Vị Xuyên-', 'vixuyen', null),
        (656, 45, '25', '227', 'Thành phố Việt Trì', 'Thành phố Việt Trì', 'Việt Trì', null, '-227-Thành phố Việt Trì-Việt Trì-', 'viettri', null),
        (657, 3, '24', '222', 'Huyện Việt Yên', 'Huyện Việt Yên', 'Việt Yên', null, '-222-Huyện Việt Yên-Việt Yên-', 'vietyen', null),
        (658, 42, '40', '412', 'Thành phố Vinh', 'Thành phố Vinh', 'Vinh', null, '-412-Thành phố Vinh-Vinh-', 'vinh', null),
        (659, 28, '31', '316', 'Huyện Vĩnh Bảo', 'Huyện Vĩnh Bảo', 'Vĩnh Bảo', null, '-316-Huyện Vĩnh Bảo-Vĩnh Bảo-', 'vinhbao', null),
        (660, 52, '94', '950', 'Thị xã Vĩnh Châu', 'Thị xã Vĩnh Châu', 'Vĩnh Châu', null, '-950-Thị xã Vĩnh Châu-Vĩnh Châu-', 'vinhchau', null),
        (661, 19, '75', '735', 'Huyện Vĩnh Cửu', 'Huyện Vĩnh Cửu', 'Vĩnh Cửu', null, '-735-Huyện Vĩnh Cửu-Vĩnh Cửu-', 'vinhcuu', null),
        (662, 40, '80', '797', 'Huyện Vĩnh Hưng', 'Huyện Vĩnh Hưng', 'Vĩnh Hưng', null, '-797-Huyện Vĩnh Hưng-Vĩnh Hưng-', 'vinhhung', null),
        (663, 51, '45', '464', 'Huyện Vĩnh Linh', 'Huyện Vĩnh Linh', 'Vĩnh Linh', null, '-464-Huyện Vĩnh Linh-Vĩnh Linh-', 'vinhlinh', null),
        (664, 62, '86', '855', 'Thành phố Vĩnh Long', 'Thành phố Vĩnh Long', 'Vĩnh Long', null, '-855-Thành phố Vĩnh Long-Vĩnh Long-', 'vinhlong', null),
        (665, 57, '38', '393', 'Huyện Vĩnh Lộc', 'Huyện Vĩnh Lộc', 'Vĩnh Lộc', null, '-393-Huyện Vĩnh Lộc-Vĩnh Lộc-', 'vinhloc', null),
        (666, 5, '95', '958', 'Huyện Vĩnh Lợi', 'Huyện Vĩnh Lợi', 'Vĩnh Lợi', null, '-958-Huyện Vĩnh Lợi-Vĩnh Lợi-', 'vinhloi', null),
        (667, 11, '52', '546', 'Huyện Vĩnh Thạnh', 'Huyện Vĩnh Thạnh', 'Vĩnh Thạnh', null, '-546-Huyện Vĩnh Thạnh-Vĩnh Thạnh-', 'vinhthanh', null),
        (668, 13, '92', '924', 'Huyện Vĩnh Thạnh', 'Huyện Vĩnh Thạnh', 'Vĩnh Thạnh', null, '-924-Huyện Vĩnh Thạnh-Vĩnh Thạnh-', 'vinhthanh', null),
        (669, 34, '91', '910', 'Huyện Vĩnh Thuận', 'Huyện Vĩnh Thuận', 'Vĩnh Thuận', null, '-910-Huyện Vĩnh Thuận-Vĩnh Thuận-', 'vinhthuan', null),
        (670, 63, '26', '252', 'Huyện Vĩnh Tường', 'Huyện Vĩnh Tường', 'Vĩnh Tường', null, '-252-Huyện Vĩnh Tường-Vĩnh Tường-', 'vinhtuong', null),
        (671, 63, '26', '243', 'Thành phố Vĩnh Yên', 'Thành phố Vĩnh Yên', 'Vĩnh Yên', null, '-243-Thành phố Vĩnh Yên-Vĩnh Yên-', 'vinhyen', null),
        (672, 56, '19', '170', 'Huyện Võ Nhai', 'Huyện Võ Nhai', 'Võ Nhai', null, '-170-Huyện Võ Nhai-Võ Nhai-', 'vonhai', null),
        (673, 26, '42', '441', 'Huyện Vũ Quang', 'Huyện Vũ Quang', 'Vũ Quang', null, '-441-Huyện Vũ Quang-Vũ Quang-', 'vuquang', null),
        (674, 55, '34', '344', 'Huyện Vũ Thư', 'Huyện Vũ Thư', 'Vũ Thư', null, '-344-Huyện Vũ Thư-Vũ Thư-', 'vuthu', null),
        (675, 41, '36', '359', 'Huyện Vụ Bản', 'Huyện Vụ Bản', 'Vụ Bản', null, '-359-Huyện Vụ Bản-Vụ Bản-', 'vuban', null),
        (676, 62, '86', '859', 'Huyện  Vũng Liêm', 'Huyện  Vũng Liêm', ' Vũng Liêm', null, '-859-Huyện  Vũng Liêm-Vũng Liêm-', 'vungliem', null),
        (677, 2, '77', '747', 'Thành phố Vũng Tàu', 'Thành phố Vũng Tàu', 'TP Vũng Tàu', null, '-747-Thành phố Vũng Tàu-Vũng Tàu-', 'tpvungtau', null),
        (678, 22, '02', '033', 'Huyện Xín Mần', 'Huyện Xín Mần', 'Xín Mần', null, '-033-Huyện Xín Mần-Xín Mần-', 'xinman', null),
        (679, 19, '75', '741', 'Huyện Xuân Lộc', 'Huyện Xuân Lộc', 'Xuân Lộc', null, '-741-Huyện Xuân Lộc-Xuân Lộc-', 'xuanloc', null),
        (680, 41, '36', '364', 'Huyện Xuân Trường', 'Huyện Xuân Trường', 'Xuân Trường', null, '-364-Huyện Xuân Trường-Xuân Trường-', 'xuantruong', null),
        (681, 2, '77', '751', 'Huyện Xuyên Mộc', 'Huyện Xuyên Mộc', 'Xuyên Mộc', null, '-751-Huyện Xuyên Mộc-Xuyên Mộc-', 'xuyenmoc', null),
        (682, 41, '36', '360', 'Huyện Ý Yên', 'Huyện Ý Yên', 'Ý Yên', null, '-360-Huyện Ý Yên-Ý Yên-', 'yyen', null),
        (683, 64, '15', '132', 'Thành phố Yên Bái', 'Thành phố Yên Bái', 'Yên Bái', null, '-132-Thành phố Yên Bái-Yên Bái-', 'yenbai', null),
        (684, 64, '15', '141', 'Huyện Yên Bình', 'Huyện Yên Bình', 'Yên Bình', null, '-141-Huyện Yên Bình-Yên Bình-', 'yenbinh', null),
        (685, 53, '14', '124', 'Huyện Yên Châu', 'Huyện Yên Châu', 'Yên Châu', null, '-124-Huyện Yên Châu-Yên Châu-', 'yenchau', null),
        (686, 3, '24', '221', 'Huyện Yên Dũng', 'Huyện Yên Dũng', 'Yên Dũng', null, '-221-Huyện Yên Dũng-Yên Dũng-', 'yendung', null),
        (687, 57, '38', '394', 'Huyện Yên Định', 'Huyện Yên Định', 'Yên Định', null, '-394-Huyện Yên Định-Yên Định-', 'yendinh', null),
        (688, 43, '37', '375', 'Huyện Yên Khánh', 'Huyện Yên Khánh', 'Yên Khánh', null, '-375-Huyện Yên Khánh-Yên Khánh-', 'yenkhanh', null),
        (689, 63, '26', '251', 'Huyện Yên Lạc', 'Huyện Yên Lạc', 'Yên Lạc', null, '-251-Huyện Yên Lạc-Yên Lạc-', 'yenlac', null),
        (690, 45, '25', '234', 'Huyện Yên Lập', 'Huyện Yên Lập', 'Yên Lập', null, '-234-Huyện Yên Lập-Yên Lập-', 'yenlap', null),
        (691, 22, '02', '028', 'Huyện Yên Minh', 'Huyện Yên Minh', 'Yên Minh', null, '-028-Huyện Yên Minh-Yên Minh-', 'yenminh', null),
        (692, 43, '37', '377', 'Huyện Yên Mô', 'Huyện Yên Mô', 'Yên Mô', null, '-377-Huyện Yên Mô-Yên Mô-', 'yenmo', null),
        (693, 32, '33', '327', 'Huyện Yên Mỹ', 'Huyện Yên Mỹ', 'Yên Mỹ', null, '-327-Huyện Yên Mỹ-Yên Mỹ-', 'yenmy', null),
        (694, 6, '27', '258', 'Huyện Yên Phong', 'Huyện Yên Phong', 'Yên Phong', null, '-258-Huyện Yên Phong-Yên Phong-', 'yenphong', null),
        (695, 61, '08', '075', 'Huyện Yên Sơn', 'Huyện Yên Sơn', 'Yên Sơn', null, '-075-Huyện Yên Sơn-Yên Sơn-', 'yenson', null),
        (696, 42, '40', '426', 'Huyện Yên Thành', 'Huyện Yên Thành', 'Yên Thành', null, '-426-Huyện Yên Thành-Yên Thành-', 'yenthanh', null),
        (697, 3, '24', '215', 'Huyện Yên Thế', 'Huyện Yên Thế', 'Yên Thế', null, '-215-Huyện Yên Thế-Yên Thế-', 'yenthe', null),
        (698, 31, '17', '158', 'Huyện Yên Thủy', 'Huyện Yên Thủy', 'Yên Thủy', null, '-158-Huyện Yên Thủy-Yên Thủy-', 'yenthuy', null),
        (2307, 16, '66', '654', 'Huyện Krông Pắk', 'Huyện Krông Pắk', 'Krông Pắk', null, '-654-Huyện Krông Pắk-Krông Pắk-', 'krongpak', null),
        (2308, 42, '40', null, 'Thị xã Hoàng Mai', 'Hoàng Mai', 'Hoàng Mai', null, null, 'hoangmai', null),
        (2309, 59, '82', '817', 'Thị xã Cai Lậy', 'Thị xã Cai Lậy', 'TX Cai Lậy', null, '-820-Huyện Cai Lậy-Cai Lậy-Tx Cai Lậy-Thị xã Cai Lậy-Tx. Cai Lậy-Tx.Cai Lậy-', 'txcailay', null),
        (2310, 47, '44', '458', 'Thị xã Ba Đồn', 'Thị xã Ba Đồn', 'Ba Đồn', null, '-2310-Thị xã Ba Đồn-Ba Đồn-', 'badon', null),
        (2311, 8, '74', '726', 'Huyện Bắc Tân Uyên', 'Huyện Bắc Tân Uyên', 'Bắc Tân Uyên', null, '-726-Huyện Bắc Tân Uyên-Bắc Tân Uyên-', 'bactanuyen', null),
        (2312, 8, '74', '719', 'Huyện Bàu Bàng', 'Huyện Bàu Bàng', 'Bàu Bàng', null, '-719-Huyện Bàu Bàng-Bàu Bàng-', 'baubang', null),
        (2313, 50, '22', '0', 'Huyện Yên Hưng', 'Huyện Yên Hưng', 'Yên Hưng', null, '-2313-Huyện Yên Hưng-Yên Hưng-', 'yenhung', null),
        (2314, 53, '14', '128', 'Huyện Vân Hồ', 'Huyện Vân Hồ', 'Vân Hồ', null, '-2314-Huyện Vân Hồ-Vân Hồ-', 'vanho', null),
        (2315, 40, '80', '', 'Thị xã Kiến Tường', 'Thị xã Kiến Tường', 'Kiến Tường', null, '-Thị xã Kiến Tường-Kiến Tường-', 'kientuong', null),
        (2316, 24, '01', '019', 'Quận Nam Từ Liêm', 'Quận Nam Từ Liêm', 'Nam Từ Liêm', null, '-019-Quận Nam Từ Liêm-Nam Từ Liêm-', 'namtuliem', null),
        (2317, 9, '70', '698', 'Huyện Phú Riềng', 'Huyện Phú Riềng', 'Phú Riềng', null, '-2317-Huyn Phú Riềng-Phú Riềng-', 'phurieng', null),
        (2319, 29, '93', '937', 'Thị xã Long Mỹ', 'Thị xã Long Mỹ', 'Long Mỹ', null, '-937-Thị xã Long Mỹ-', 'longmy', null),
        (2322, 26, '42', '449', 'Thị xã Kỳ Anh', 'Thị xã Kỳ Anh', 'Thị xã Kỳ Anh', null, '-448-Thị xã Kỳ Anh-', 'thixakyanh', null),
        (2324, 60, '84', '851', 'Thị xã Duyên Hải', 'Thị xã Duyên Hải', 'TX Duyên Hải', null, '-Thị xã Duyên Hải-', 'txduyenhai', null),
        (2325, 35, '62', '618', 'Huyện IA H’DRAI', 'Huyện IA H’DRAI', 'IA H’DRAI', null, '-618-IA H’DRAI-', 'iahdrai', null);

