export const SALES_CONCERN = {
    TIME: "TIME",
    REVENUE: "REVENUE",
    DISCOUNT: "DISCOUNT",
    SALE_RETURN: "SALE_RETURN",
    EMPLOYEE: "EMPLOYEE"
};

export const PRODUCTS_CONCERN = {
    SALE: "SALE",
    REVENUE: "REVENUE",
    WAREHOUSE_VALUE: "WAREHOUSE_VALUE",
    INVENTORY: "INVENTORY",
    INVENTORY_DETAIL: "INVENTORY_DETAIL",
    CANCEL: 'CANCEL',
    EMPLOYEE: 'EMPLOYEE',
    CUSTOMER: 'CUSTOMER',

};