// TODO::remove
export const CODE_SUCCESS_RESPONSE = 200;
export const ERROR_CODE_SYSTEM_ERROR = 500;
export const ERROR_CODE_BAD_REQUEST = 400;
export const ERROR_CODE_UNAUTHORIZED = 401;
export const ERROR_CODE_FORBIDDEN = 403;
export const ERROR_CODE_TOKEN_EXPIRED = 402;
export const ERROR_CODE_API_NOT_FOUND = 404;
export const ERROR_CODE_UPLOAD_ERROR = 409;
export const ERROR_CODE_INVALID_PARAMETER = 422;
export const ERROR_CODE_INCORRECT_PASSWORD = 303;
export const ERROR_CODE_CREDENTIAL_NOT_EXIST = 304;
export const ERROR_CODE_OLD_PASSWORD_NOT_CORRECT = 305;
export const ERROR_CODE_EMAIL_EXIST = 306;
export const ERROR_CODE_ITEM_NOT_EXIST = 308;
export const ERROR_CODE_CHANGE_STATUS_NOT_SUCCESS = 309;
export const ERROR_CODE_IMPORT_CSV_FAIL = 310;

export const HttpStatusCode = {
  SUCCESS_RESPONSE: 200,
  SYSTEM_ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  TOKEN_EXPIRED: 402,
  NOT_FOUND: 404,
  UPLOAD_ERROR: 409,
  INVALID_PARAMETER: 422,
  INCORRECT_PASSWORD: 303,
  CREDENTIAL_NOT_EXIST: 304,
  OLD_PASSWORD_NOT_CORRECT: 305,
  EMAIL_EXIST: 306,
  ITEM_NOT_EXIST: 308,
  CHANGE_STATUS_NOT_SUCCESS: 309,
  IMPORT_CSV_FAIL: 310,
};
