ALTER TABLE inbounds
MODIFY COLUMN totalPrice BIGINT;

ALTER TABLE inbounds
MODIFY COLUMN paid BIGINT;

ALTER TABLE inbounds
MODIFY COLUMN debt BIGINT;

ALTER TABLE payments
MODIFY COLUMN amount BIGINT;

ALTER TABLE payments
MODIFY COLUMN totalAmount BIGINT;

ALTER TABLE orders
MODIFY COLUMN totalPrice BIGINT;

ALTER TABLE orders
MODIFY COLUMN cashOfCustomer BIGINT;

ALTER TABLE user_logs
MODIFY COLUMN amount BIGINT;

ALTER TABLE transactions
MODIFY COLUMN value BIGINT;